// apps/web-angular/src/app/shared/location/location-fields/location-fields.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  inject,
  input,
  linkedSignal,
  output,
} from '@angular/core';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { RegionContext } from '../../../core/region/region-context.service';
import { RegionsStore } from '../../regions/regions.store';
import { ErrorStateComponent } from '../../ui/error-state/error-state.component';
import { SkeletonComponent } from '../../ui/skeleton/skeleton.component';
import { CITY_MAX_LENGTH, LocationDraft } from '../my-location.store';

const EMPTY_DRAFT: LocationDraft = {
  countryCode: '',
  subdivisionCode: '',
  city: '',
  showCity: true,
};

/**
 * "Where are you?" fields (ADR 0017): platform region → country → state/province from `GET
 * /regions`, an optional city and the "show my city on my profile" switch. Simple pickers only:
 * no map, no GPS, no geocoding. Used by onboarding and Settings → Location.
 */
@Component({
  selector: 'app-location-fields',
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
    ErrorStateComponent,
    SkeletonComponent,
  ],
  template: `
    @if (!regions.loaded() && regions.error(); as error) {
      <app-error-state
        compact
        title="We could not load the list of places"
        [message]="error.message"
        (retry)="regions.load()"
      />
    } @else if (!regions.loaded()) {
      <div class="location-fields__loading" aria-busy="true">
        <span class="visually-hidden">Loading countries and states</span>
        <app-skeleton height="56px" />
        <app-skeleton height="56px" />
      </div>
    } @else {
      <div class="location-fields" role="group" aria-label="Your location">
        <mat-form-field appearance="outline">
          <mat-label>Region</mat-label>
          <mat-select
            data-testid="location-region"
            [value]="region()"
            (selectionChange)="onRegion($event.value)"
          >
            @for (option of regions.regions(); track option.code) {
              <mat-option [value]="option.code">{{ option.name }}</mat-option>
            }
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Country</mat-label>
          <mat-select
            data-testid="location-country"
            required
            [value]="draft().countryCode || null"
            (selectionChange)="onCountry($event.value)"
          >
            @for (country of countries(); track country.code) {
              <mat-option [value]="country.code">{{ country.name }}</mat-option>
            }
          </mat-select>
        </mat-form-field>

        @if (!wholeCountry()) {
          <mat-form-field appearance="outline">
            <mat-label>State or province</mat-label>
            <mat-select
              data-testid="location-subdivision"
              required
              [disabled]="!draft().countryCode"
              [value]="draft().subdivisionCode || null"
              (selectionChange)="onSubdivision($event.value)"
            >
              @for (subdivision of subdivisions(); track subdivision.code) {
                <mat-option [value]="subdivision.code">{{ subdivision.name }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
        }

        <mat-form-field appearance="outline" class="location-fields__city">
          <mat-label>City (optional)</mat-label>
          <input
            matInput
            data-testid="location-city"
            autocomplete="address-level2"
            [maxLength]="cityMax"
            [value]="draft().city"
            (input)="onCity($event)"
          />
          <mat-hint>Only shown on your profile, never used to locate you.</mat-hint>
          <mat-hint align="end">{{ draft().city.length }} / {{ cityMax }}</mat-hint>
        </mat-form-field>

        <mat-slide-toggle
          class="location-fields__show-city"
          data-testid="location-show-city"
          [checked]="draft().showCity"
          (change)="onShowCity($event.checked)"
        >
          Show my city on my profile
        </mat-slide-toggle>

        @if (showErrors() && missing(); as message) {
          <p class="location-fields__error" role="alert">{{ message }}</p>
        }
      </div>
    }
  `,
  styles: `
    .location-fields {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));
      gap: var(--spacing-2) var(--spacing-3);
      align-items: start;
    }
    .location-fields__city {
      grid-column: 1 / -1;
    }
    .location-fields__show-city {
      grid-column: 1 / -1;
      margin-top: var(--spacing-2);
    }
    .location-fields__loading {
      display: grid;
      gap: var(--spacing-3);
    }
    .location-fields__error {
      grid-column: 1 / -1;
      margin: 0;
      color: var(--color-danger);
      font-size: var(--font-size-sm);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LocationFieldsComponent {
  protected readonly regions = inject(RegionsStore);
  private readonly context = inject(RegionContext);

  readonly value = input<LocationDraft | null>(null);
  /** Show "choose a country / state" messages (after a save attempt). */
  readonly showErrors = input(false, { transform: booleanAttribute });
  readonly valueChange = output<LocationDraft>();

  protected readonly cityMax = CITY_MAX_LENGTH;
  protected readonly draft = linkedSignal(() => this.value() ?? EMPTY_DRAFT);
  /**
   * Region whose countries are listed: the chosen country's; without a country, the region picked
   * last (a region change clears the country), else the browsed one.
   */
  protected readonly region = linkedSignal<string, string>({
    source: () => this.regions.country(this.draft().countryCode)?.regionCode ?? '',
    computation: (fromCountry, previous) =>
      fromCountry || previous?.value || this.context.current(),
  });
  protected readonly countries = computed(
    () => this.regions.region(this.region())?.countries.filter((country) => country.active) ?? [],
  );
  protected readonly subdivisions = computed(
    () => this.regions.country(this.draft().countryCode)?.subdivisions ?? [],
  );
  /** A territory or micro-state: its single pseudo-subdivision is chosen with the country. */
  protected readonly wholeCountry = computed(() => {
    const subdivisions = this.subdivisions();
    return subdivisions.length === 1 && subdivisions[0].wholeCountry;
  });
  protected readonly missing = computed(() => {
    const draft = this.draft();
    if (!draft.countryCode) {
      return 'Choose your country.';
    }
    if (!draft.subdivisionCode) {
      return 'Choose your state or province.';
    }
    return null;
  });

  constructor() {
    void this.regions.load();
  }

  protected onRegion(code: string): void {
    this.region.set(code);
    if (this.regions.country(this.draft().countryCode)?.regionCode !== code) {
      this.emit({ ...this.draft(), countryCode: '', subdivisionCode: '' });
    }
  }

  protected onCountry(code: string): void {
    const subdivisions = this.regions.country(code)?.subdivisions ?? [];
    const only = subdivisions.length === 1 && subdivisions[0].wholeCountry ? subdivisions[0] : null;
    this.emit({ ...this.draft(), countryCode: code, subdivisionCode: only?.code ?? '' });
  }

  protected onSubdivision(code: string): void {
    this.emit({ ...this.draft(), subdivisionCode: code });
  }

  protected onCity(event: Event): void {
    const city = (event.target as HTMLInputElement).value.slice(0, CITY_MAX_LENGTH);
    this.emit({ ...this.draft(), city });
  }

  protected onShowCity(showCity: boolean): void {
    this.emit({ ...this.draft(), showCity });
  }

  private emit(next: LocationDraft): void {
    this.draft.set(next);
    this.valueChange.emit(next);
  }
}

// apps/mobile/src/features/location/LocationFields.tsx
import { StyleSheet, Text, View } from 'react-native';

import { useRegions } from '@/src/api/hooks/regions';
import { ErrorState } from '@/src/components/ui/ErrorState';
import { FormMessage, SwitchRow } from '@/src/components/ui/FormControls';
import { SelectSheet, type SelectOption } from '@/src/components/ui/SelectSheet';
import { SkeletonList } from '@/src/components/ui/Skeleton';
import { TextField } from '@/src/components/ui/TextField';
import { CITY_MAX_LENGTH } from '@/src/lib/place';
import { spacing, textStyle, useTheme } from '@/src/theme';

import {
  countriesOf,
  countryOf,
  isWholeCountry,
  missingField,
  withCountry,
  withRegion,
  type LocationDraft,
} from './locationDraft';

export interface LocationFieldsProps {
  value: LocationDraft;
  onChange: (draft: LocationDraft) => void;
  /** Show what is missing (after a save attempt). */
  showErrors?: boolean;
  disabled?: boolean;
}

/**
 * "Where are you?" (ADR 0017, the web's `app-location-fields`): platform region → country →
 * state or province pickers fed by `GET /regions`, an optional city (shown on the collector's own
 * profile only) and "show my city on my profile". No map, no GPS, no geocoding.
 */
export function LocationFields({ value, onChange, showErrors, disabled }: LocationFieldsProps) {
  const { palette } = useTheme();
  const regions = useRegions();

  if (regions.isPending) {
    return <SkeletonList rows={3} rowHeight={52} />;
  }
  if (!regions.data) {
    return (
      <ErrorState
        title="We could not load the list of places"
        error={regions.error}
        onRetry={() => void regions.refetch()}
        compact
      />
    );
  }
  const all = regions.data.regions;
  const regionOptions: SelectOption<string>[] = all.map((region) => ({
    value: region.code,
    label: region.name,
  }));
  const countryOptions: SelectOption<string>[] = [
    { value: '', label: 'Choose a country' },
    ...countriesOf(all, value.regionCode).map((country) => ({
      value: country.code,
      label: country.name,
    })),
  ];
  const country = countryOf(all, value.countryCode);
  const subdivisionOptions: SelectOption<string>[] = [
    { value: '', label: 'Choose a state or province' },
    ...(country?.subdivisions ?? []).map((subdivision) => ({
      value: subdivision.code,
      label: subdivision.name,
    })),
  ];
  const missing = showErrors ? missingField(value) : null;

  return (
    <View style={styles.root} testID="location-fields">
      <SelectSheet
        label="Region"
        options={regionOptions}
        value={value.regionCode}
        onChange={(regionCode) => onChange(withRegion(value, regionCode))}
        disabled={disabled}
        testID="location-region"
      />
      <SelectSheet
        label="Country"
        options={countryOptions}
        value={value.countryCode}
        onChange={(countryCode) => onChange(withCountry(value, all, countryCode))}
        disabled={disabled}
        testID="location-country"
      />
      {country && !isWholeCountry(country) ? (
        <SelectSheet
          label="State or province"
          options={subdivisionOptions}
          value={value.subdivisionCode}
          onChange={(subdivisionCode) => onChange({ ...value, subdivisionCode })}
          disabled={disabled}
          testID="location-subdivision"
        />
      ) : null}
      <TextField
        label="City (optional)"
        hint="Only shown on your profile, never used to locate you."
        value={value.city}
        maxLength={CITY_MAX_LENGTH}
        autoComplete="off"
        editable={!disabled}
        onChangeText={(city) => onChange({ ...value, city })}
        testID="location-city"
      />
      <SwitchRow
        label="Show my city on my profile"
        value={value.showCity}
        onChange={(showCity) => onChange({ ...value, showCity })}
        disabled={disabled}
        testID="location-show-city"
      />
      <Text style={[textStyle('sm'), { color: palette.textMuted }]}>
        Others only see your state or province and your country.
      </Text>
      {missing ? <FormMessage testID="location-missing">{missing}</FormMessage> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  root: { gap: spacing[3] },
});
