// apps/web-angular/src/app/features/search/card-holders/holder-row.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import type { CardHolderResult } from '@orenji/api-client';
import { editionLabel, languageLabel } from '../../../shared/catalog/catalog-labels';
import { CardImageComponent } from '../../../shared/catalog/card-image/card-image.component';
import { distanceBucketLabel } from '../../../shared/domain/location-labels';
import {
  badgeFreshness,
  formatPrice,
  printingCode,
  printingImageUrl,
} from '../../../shared/inventory/inventory-labels';
import { ItemChipsComponent } from '../../../shared/inventory/item-chips/item-chips.component';
import { MakeOfferButtonComponent } from '../../../shared/offers/make-offer-button.component';
import { offerTargetFromItem, sellerFromMarker } from '../../../shared/offers/offer-target';
import { AvatarComponent } from '../../../shared/ui/avatar/avatar.component';
import { FreshnessBadgeComponent } from '../../../shared/ui/freshness-badge/freshness-badge.component';

/**
 * One "who near me has this card" result: the listed copy (picture, printing, chips, price,
 * freshness, public note) and its holder (approximate place and distance only), with "Make an
 * offer" when the copy accepts offers.
 */
@Component({
  selector: 'app-holder-row',
  imports: [
    RouterLink,
    MatButtonModule,
    MatIconModule,
    AvatarComponent,
    CardImageComponent,
    FreshnessBadgeComponent,
    ItemChipsComponent,
    MakeOfferButtonComponent,
  ],
  template: `
    @let r = result();
    <article class="hr" [attr.aria-label]="r.collector.displayName + ', ' + code()">
      <app-card-image
        class="hr__img"
        [src]="image()"
        [alt]="r.item.card.name"
        [game]="r.item.card.game"
      />
      <div class="hr__item">
        <p class="hr__code mono">{{ code() }}</p>
        <p class="hr__meta">
          {{ r.item.printing.setName }} · {{ language() }} · {{ edition() }}
          @if (r.item.quantity > 1) {
            · ×{{ r.item.quantity }}
          }
        </p>
        <app-item-chips
          [condition]="r.item.condition"
          [availability]="r.item.availability"
          [acceptsOffers]="r.item.acceptsOffers"
        />
        @if (r.item.publicNotes) {
          <p class="hr__note">“{{ r.item.publicNotes }}”</p>
        }
        <app-freshness-badge compact [state]="freshness()" [label]="r.item.freshness.label" />
      </div>
      <div class="hr__side">
        <p class="hr__price" data-testid="holder-price">{{ price() }}</p>
        <div class="hr__owner">
          <app-avatar
            size="sm"
            [src]="r.collector.avatarUrl"
            [name]="r.collector.displayName"
            [decorative]="true"
          />
          <div class="hr__owner-text">
            <a class="hr__owner-name" [routerLink]="['/collectors', r.collector.handle]">{{
              r.collector.displayName
            }}</a>
            <span class="hr__place">
              {{ r.collector.publicLabel }}
              @if (distance(); as distance) {
                · {{ distance }}
              }
            </span>
          </div>
        </div>
        <app-make-offer-button appearance="filled" compact [target]="offerTarget()" />
        @if (r.item.binder; as binder) {
          <a matButton="outlined" class="hr__binder" [routerLink]="['/binders', binder.id]">
            <mat-icon aria-hidden="true">menu_book</mat-icon>
            View binder
          </a>
        }
      </div>
    </article>
  `,
  styles: `
    :host {
      display: block;
    }
    .hr {
      display: grid;
      grid-template-columns: 72px 1fr auto;
      gap: var(--spacing-3) var(--spacing-4);
      padding: var(--spacing-3);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      background: var(--color-surface);
      transition: box-shadow var(--motion-duration-fast) var(--motion-easing-standard);
    }
    .hr:hover,
    .hr:focus-within {
      box-shadow: var(--elevation-menu);
    }
    .hr__img {
      width: 72px;
    }
    .hr__item {
      display: flex;
      flex-direction: column;
      gap: 4px;
      min-width: 0;
    }
    .hr__code {
      margin: 0;
      font-weight: var(--font-weight-semibold);
    }
    .hr__meta,
    .hr__place {
      margin: 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .hr__note {
      margin: 0;
      font-size: var(--font-size-sm);
      font-style: italic;
    }
    .hr__side {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: var(--spacing-2);
      text-align: right;
    }
    .hr__price {
      margin: 0;
      font-family: var(--font-display);
      font-size: var(--font-size-xl);
      font-weight: var(--font-weight-semibold);
    }
    .hr__owner {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
    }
    .hr__owner-text {
      display: flex;
      flex-direction: column;
    }
    .hr__owner-name {
      color: var(--color-ink);
      font-weight: var(--font-weight-semibold);
    }
    @media (max-width: 599px) {
      .hr {
        grid-template-columns: 56px 1fr;
      }
      .hr__img {
        width: 56px;
      }
      .hr__side {
        grid-column: 1 / -1;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        text-align: left;
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HolderRowComponent {
  readonly result = input.required<CardHolderResult>();
  readonly signedIn = input(false);

  protected readonly offerTarget = computed(() =>
    offerTargetFromItem(this.result().item, sellerFromMarker(this.result().collector)),
  );
  protected readonly code = computed(() => printingCode(this.result().item.printing));
  protected readonly image = computed(() => printingImageUrl(this.result().item.printing));
  protected readonly language = computed(() => languageLabel(this.result().item.language));
  protected readonly edition = computed(() => editionLabel(this.result().item.edition));
  protected readonly freshness = computed(() => badgeFreshness(this.result().item.freshness.state));
  protected readonly distance = computed(() =>
    this.signedIn() ? distanceBucketLabel(this.result().collector.distanceBucket) : null,
  );
  protected readonly price = computed(() => {
    const item = this.result().item;
    return (
      formatPrice(item.askingPrice, item.currency) ??
      (item.acceptsOffers ? 'Make an offer' : 'No price')
    );
  });
}

// apps/mobile/src/features/holders/HolderRow.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { memo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import type { CardHolderResult } from '@/src/api/types';
import { Avatar } from '@/src/components/ui/Avatar';
import { Badge, type CardCondition } from '@/src/components/ui/Badge';
import { Button } from '@/src/components/ui/Button';
import { CardImage } from '@/src/components/ui/CardImage';
import { MakeOfferButton } from '@/src/features/offers/MakeOfferButton';
import { offerTargetFromItem, sellerFromMarker } from '@/src/features/offers/offerTarget';
import {
  editionLabel,
  formatMoney,
  languageName,
  printingCode,
  printingImageUrl,
} from '@/src/lib/catalog';
import { distanceBucketLabel } from '@/src/lib/formatDistanceBucket';
import {
  availabilityLabel,
  badgeFreshness,
  conditionLabel,
  isKnownCondition,
} from '@/src/lib/inventory';
import { GENERIC_AREA_LABEL, placeLabel } from '@/src/lib/location';
import { fontFamily, fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

/**
 * One "who near me has this card" result (the web's `app-holder-row`): the listed copy (picture,
 * printing, set, language, edition, copies, condition, availability, offers, public note, price,
 * freshness) and its holder (name, approximate place and the API's distance bucket only), with
 * "Make an offer" when the copy accepts one and "View binder" when it sits in a public binder.
 */
export const HolderRow = memo(function HolderRow({ result }: { result: CardHolderResult }) {
  const { palette } = useTheme();
  const router = useRouter();
  const { collector, item } = result;
  const code = printingCode(item.printing);
  const price =
    formatMoney(item.askingPrice ?? null, item.currency) ??
    (item.acceptsOffers ? 'Make an offer' : 'No price');
  const place = placeLabel(collector.publicLabel) ?? GENERIC_AREA_LABEL;
  const distance = distanceBucketLabel(collector.distanceBucket);
  const meta = [item.printing.setName, languageName(item.language), editionLabel(item.edition)]
    .filter((part) => part && part !== '—')
    .join(' · ');
  return (
    <View
      testID={`holder-${item.id}`}
      accessibilityLabel={`${collector.displayName}, ${code}`}
      style={[styles.card, { backgroundColor: palette.surface, borderColor: palette.border }]}
    >
      <View style={styles.row}>
        <CardImage
          src={item.images[0]?.url ?? printingImageUrl(item.printing)}
          alt=""
          game={item.card.game}
          size="sm"
        />
        <View style={styles.text}>
          <Text style={[textStyle('sm'), styles.mono, styles.strong, { color: palette.ink }]}>
            {code}
          </Text>
          <Text style={[textStyle('xs'), { color: palette.textMuted }]} numberOfLines={2}>
            {meta}
            {item.quantity > 1 ? ` · ×${item.quantity}` : ''}
          </Text>
          <View style={styles.badges}>
            {isKnownCondition(item.condition) ? (
              <Badge variant="condition" value={item.condition as CardCondition} />
            ) : (
              <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
                {conditionLabel(item.condition)}
              </Text>
            )}
            <Tag label={availabilityLabel(item.availability)} />
            {item.acceptsOffers ? <Tag label="Offers" tone="offers" /> : null}
            <Badge variant="freshness" value={badgeFreshness(item.freshness.state)} />
          </View>
          {item.publicNotes ? (
            <Text style={[textStyle('xs'), styles.note, { color: palette.textMuted }]}>
              “{item.publicNotes}”
            </Text>
          ) : null}
        </View>
        <Text
          testID={`holder-${item.id}-price`}
          style={[textStyle('lg', 'heading'), styles.strong, { color: palette.ink }]}
        >
          {price}
        </Text>
      </View>
      <Pressable
        accessibilityRole="link"
        accessibilityLabel={`${collector.displayName}, ${place}${distance ? `, ${distance}` : ''}. Opens their profile.`}
        onPress={() =>
          router.push({ pathname: '/collectors/[id]', params: { id: collector.handle } })
        }
        testID={`holder-${item.id}-collector`}
        style={({ pressed }) => [styles.owner, pressed && styles.pressed]}
      >
        <Avatar src={collector.avatarUrl} name={collector.displayName} size={32} />
        <View style={styles.grow}>
          <Text style={[textStyle('sm'), styles.strong, { color: palette.ink }]} numberOfLines={1}>
            {collector.displayName}
          </Text>
          <Text style={[textStyle('xs'), { color: palette.textMuted }]} numberOfLines={1}>
            {place}
            {distance ? ` · ${distance}` : ''}
          </Text>
        </View>
        <MaterialCommunityIcons name="chevron-right" size={20} color={palette.textDisabled} />
      </Pressable>
      <View style={styles.actions}>
        <MakeOfferButton
          target={offerTargetFromItem(item, sellerFromMarker(collector))}
          style={styles.action}
        />
        {item.binder ? (
          <Button
            label="View binder"
            icon="book-open-variant"
            variant="ghost"
            onPress={() =>
              router.push({
                pathname: '/binders/[id]',
                params: { id: item.binder?.id ?? '', view: 'public' },
              })
            }
            style={styles.action}
            testID={`holder-${item.id}-binder`}
          />
        ) : null}
      </View>
    </View>
  );
});

function Tag({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'offers' }) {
  const { palette } = useTheme();
  const color = tone === 'offers' ? palette.availability.offers : palette.textMuted;
  return (
    <View style={[styles.tag, { borderColor: tone === 'offers' ? color : palette.border }]}>
      <Text style={[textStyle('xs'), { color }]}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  card: { borderRadius: radius.md, borderWidth: 1, padding: spacing[3], gap: spacing[2] },
  row: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing[3] },
  text: { flex: 1, gap: 4 },
  mono: { fontFamily: fontFamily.mono },
  strong: { fontWeight: fontWeight.semibold },
  note: { fontStyle: 'italic' },
  badges: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing[1] },
  tag: {
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingHorizontal: spacing[2],
    paddingVertical: 1,
  },
  owner: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  grow: { flex: 1 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  action: { flexGrow: 1, minHeight: 40, paddingVertical: spacing[2] },
  pressed: { opacity: 0.8 },
});
