// apps/mobile/src/features/legal/AgeConfirmationCheckbox.tsx
import { StyleSheet, Text, View } from 'react-native';

import { Checkbox } from '@/src/components/ui/FormControls';
import { radius, spacing, textStyle, useTheme } from '@/src/theme';

import {
  AGE_CONFIRMATION_ERROR,
  AGE_CONFIRMATION_ERROR_FR,
  AGE_CONFIRMATION_LABEL_EN,
  AGE_CONFIRMATION_LABEL_FR,
} from './ageConfirmation';

export interface AgeConfirmationCheckboxProps {
  checked: boolean;
  onChange: (checked: boolean) => void;
  /** Show the validation message (the parent sets it after a submit attempt). */
  showError: boolean;
  disabled?: boolean;
  testID?: string;
}

/**
 * The 18+ confirmation checkbox (web: `app-age-confirmation-checkbox`): never ticked by default,
 * never part of "Accept all", labelled in English and French; the parent records the
 * confirmation server-side with `POST /me/consents` (`AGE_CONFIRMATION`).
 */
export function AgeConfirmationCheckbox({
  checked,
  onChange,
  showError,
  disabled,
  testID = 'age-confirmation',
}: AgeConfirmationCheckboxProps) {
  const { palette } = useTheme();
  const error = showError && !checked;
  return (
    <View
      style={[
        styles.box,
        { borderColor: error ? palette.danger : palette.border, backgroundColor: palette.surface },
      ]}
      testID={`${testID}-box`}
    >
      <Checkbox
        label={AGE_CONFIRMATION_LABEL_EN}
        checked={checked}
        onChange={onChange}
        error={error}
        disabled={disabled}
        testID={testID}
      >
        <Text style={[textStyle('sm'), { color: palette.ink }]}>{AGE_CONFIRMATION_LABEL_EN}</Text>
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {AGE_CONFIRMATION_LABEL_FR}
        </Text>
      </Checkbox>
      {error ? (
        <View accessibilityRole="alert" testID={`${testID}-error`} style={styles.error}>
          <Text style={[textStyle('sm'), { color: palette.danger }]}>{AGE_CONFIRMATION_ERROR}</Text>
          <Text style={[textStyle('sm'), { color: palette.danger }]}>
            {AGE_CONFIRMATION_ERROR_FR}
          </Text>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  box: { borderWidth: 1, borderRadius: radius.md, padding: spacing[2], gap: spacing[1] },
  error: { paddingHorizontal: spacing[2], paddingBottom: spacing[1], gap: 2 },
});

// apps/web-angular/src/app/shared/legal/age-confirmation-checkbox.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatCheckboxModule } from '@angular/material/checkbox';

/** The API's document type of the 18+ attestation (`POST /me/consents`). */
export const AGE_CONFIRMATION_TYPE = 'AGE_CONFIRMATION';

/** Checkbox wording, English and its French equivalent (Bill 96). Both are always shown. */
export const AGE_CONFIRMATION_LABEL_EN = 'I confirm I am 18 years of age or older';
export const AGE_CONFIRMATION_LABEL_FR = 'Je confirme avoir 18 ans ou plus';
export const AGE_CONFIRMATION_ERROR =
  'You must confirm that you are 18 years of age or older to use OrenjiTrade.';

/**
 * The 18+ confirmation checkbox: never ticked by default, the parent owns the `requiredTrue`
 * control and records the confirmation server-side with `POST /me/consents`
 * (`AGE_CONFIRMATION`). Self-declaration only: nothing else is asked or verified.
 */
@Component({
  selector: 'app-age-confirmation-checkbox',
  imports: [ReactiveFormsModule, MatCheckboxModule],
  template: `
    <div class="age" [attr.aria-describedby]="showError() ? 'age-confirmation-error' : null">
      <mat-checkbox class="age__box" [formControl]="control()" data-testid="age-confirmation">
        <span class="age__label">{{ labelEn }}</span>
        <span class="age__label age__label--fr" lang="fr">{{ labelFr }}</span>
      </mat-checkbox>
      @if (showError()) {
        <p class="age__error" id="age-confirmation-error" role="alert">{{ errorMessage }}</p>
      }
    </div>
  `,
  styles: `
    .age {
      padding: var(--spacing-3) var(--spacing-4);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);
      background: var(--color-surface);
    }
    .age__label {
      display: block;
    }
    .age__label--fr {
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
    }
    .age__error {
      margin: var(--spacing-1) 0 0;
      color: var(--color-danger);
      font-size: var(--font-size-sm);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AgeConfirmationCheckboxComponent {
  readonly control = input.required<FormControl<boolean>>();
  /** Show the validation message (the parent sets it after a submit attempt). */
  readonly showError = input(false);

  protected readonly labelEn = AGE_CONFIRMATION_LABEL_EN;
  protected readonly labelFr = AGE_CONFIRMATION_LABEL_FR;
  protected readonly errorMessage = AGE_CONFIRMATION_ERROR;
}
