// apps/mobile/src/features/inventory/ItemDetailsFields.tsx
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import type { BinderResponse, GameSchema } from '@/src/api/types';
import { ChoiceChips } from '@/src/components/ui/ChoiceChips';
import { SwitchRow } from '@/src/components/ui/FormControls';
import { SectionCard } from '@/src/components/ui/Layout';
import { SelectSheet } from '@/src/components/ui/SelectSheet';
import { TextField } from '@/src/components/ui/TextField';
import { editionLabel, finishLabel, languageName } from '@/src/lib/catalog';
import {
  AVAILABILITIES,
  AVAILABILITY_LABELS,
  CARD_CONDITIONS,
  conditionLabel,
  CURRENCIES,
  endsLabel,
  TEMPORARY_DURATIONS,
  VISIBILITIES,
  VISIBILITY_INFO,
} from '@/src/lib/inventory';
import { spacing, textStyle, useTheme } from '@/src/theme';

import {
  KEEP_END,
  NOTES_MAX,
  PUBLIC_NOTES_MAX,
  withCurrent,
  type DurationChoice,
  type ItemFormErrors,
  type ItemFormValue,
} from './itemForm';

const UNFILED = '__unfiled__';

export interface ItemDetailsFieldsProps {
  value: ItemFormValue;
  onChange: (patch: Partial<ItemFormValue>) => void;
  errors: ItemFormErrors;
  schema: GameSchema | null | undefined;
  binders: readonly BinderResponse[];
  /** End of the running temporary publication (edit only): offers "Keep current end". */
  currentPublicUntil?: string | null;
  disabled?: boolean;
}

/**
 * The fields of an inventory item, grouped like the web's `app-item-details-fields`: the card
 * (copies, condition, language, edition, finish from the game schema), the listing (trade / sale
 * intent, offers, asking price), visibility and binder, and notes.
 */
export function ItemDetailsFields({
  value,
  onChange,
  errors,
  schema,
  binders,
  currentPublicUntil,
  disabled = false,
}: ItemDetailsFieldsProps) {
  const { palette } = useTheme();
  const conditions = withCurrent(
    schema?.conditions?.length ? schema.conditions : CARD_CONDITIONS,
    value.condition
  );
  const languages = withCurrent(schema?.languages, value.language);
  const editions = withCurrent(schema?.editions, value.edition);
  const finishes = withCurrent(schema?.finishes, value.finish);
  const currencies = withCurrent(CURRENCIES, value.currency);
  const binder = value.binderId
    ? binders.find((candidate) => candidate.id === value.binderId)
    : null;
  // When the form opened: "Keep" the running publication end, if any.
  const [openedAt] = useState(() => Date.now());
  const runningEnd =
    currentPublicUntil && Date.parse(currentPublicUntil) > openedAt
      ? endsLabel(currentPublicUntil, openedAt)
      : null;
  const durations: { value: DurationChoice; label: string }[] = [
    ...(runningEnd ? [{ value: KEEP_END as DurationChoice, label: `Keep (${runningEnd})` }] : []),
    ...TEMPORARY_DURATIONS.map((option) => ({
      value: option.value as DurationChoice,
      label: option.label,
    })),
  ];

  return (
    <View style={styles.root}>
      <SectionCard title="Card">
        <TextField
          label="Copies"
          value={value.quantity}
          onChangeText={(quantity) => onChange({ quantity: quantity.replace(/[^\d]/g, '') })}
          keyboardType="number-pad"
          maxLength={4}
          error={errors.quantity}
          editable={!disabled}
          testID="item-quantity"
        />
        <ChoiceChips
          label="Condition"
          options={conditions.map((condition) => ({
            value: condition,
            label: conditionLabel(condition),
          }))}
          value={value.condition}
          onChange={(condition) => onChange({ condition })}
          error={errors.condition}
          disabled={disabled}
          testID="item-condition"
        />
        {languages.length > 0 ? (
          <ChoiceChips
            label="Language"
            options={languages.map((language) => ({
              value: language,
              label: languageName(language),
            }))}
            value={value.language}
            onChange={(language) => onChange({ language })}
            disabled={disabled}
            testID="item-language"
          />
        ) : null}
        {editions.length > 0 ? (
          <ChoiceChips
            label="Edition"
            options={editions.map((edition) => ({ value: edition, label: editionLabel(edition) }))}
            value={value.edition}
            onChange={(edition) => onChange({ edition })}
            disabled={disabled}
            testID="item-edition"
          />
        ) : null}
        {finishes.length > 0 ? (
          <ChoiceChips
            label="Finish"
            options={finishes.map((finish) => ({ value: finish, label: finishLabel(finish) }))}
            value={value.finish}
            onChange={(finish) => onChange({ finish })}
            disabled={disabled}
            testID="item-finish"
          />
        ) : null}
      </SectionCard>

      <SectionCard
        title="Listing"
        description="Trade, sell or keep it: what collectors may ask you for."
      >
        <ChoiceChips
          label="Available for"
          options={AVAILABILITIES.map((availability) => ({
            value: availability,
            label: AVAILABILITY_LABELS[availability],
          }))}
          value={value.availability}
          onChange={(availability) => onChange({ availability })}
          disabled={disabled}
          testID="item-availability"
        />
        <SwitchRow
          label="Accepts offers"
          help="Collectors may propose a price or a trade for this card."
          value={value.acceptsOffers}
          onChange={(acceptsOffers) => onChange({ acceptsOffers })}
          disabled={disabled}
          testID="item-accepts-offers"
        />
        <TextField
          label="Asking price (optional)"
          value={value.askingPrice}
          onChangeText={(askingPrice) => onChange({ askingPrice })}
          keyboardType="decimal-pad"
          placeholder="0.00"
          maxLength={14}
          error={errors.askingPrice}
          editable={!disabled}
          testID="item-price"
        />
        <ChoiceChips
          label="Currency"
          options={currencies.map((currency) => ({ value: currency, label: currency }))}
          value={value.currency}
          onChange={(currency) => onChange({ currency })}
          error={errors.currency}
          disabled={disabled}
          testID="item-currency"
        />
      </SectionCard>

      <SectionCard title="Visibility">
        <ChoiceChips
          label="Who can see it"
          options={VISIBILITIES.map((visibility) => ({
            value: visibility,
            label: VISIBILITY_INFO[visibility].label,
          }))}
          value={value.visibility}
          onChange={(visibility) => onChange({ visibility })}
          hint={visibilityHint(value.visibility)}
          disabled={disabled}
          testID="item-visibility"
        />
        {value.visibility === 'TEMPORARILY_PUBLIC' ? (
          <ChoiceChips
            label="Public for"
            options={durations}
            value={value.duration}
            onChange={(duration) => onChange({ duration })}
            hint="Then private again automatically."
            disabled={disabled}
            testID="item-duration"
          />
        ) : null}
        <SelectSheet
          label="Binder"
          options={[
            { value: UNFILED, label: 'No binder (unfiled)' },
            ...binders.map((candidate) => ({
              value: candidate.id,
              label: candidate.name,
              detail: VISIBILITY_INFO[candidate.visibility].label,
            })),
          ]}
          value={value.binderId ?? UNFILED}
          onChange={(binderId) => onChange({ binderId: binderId === UNFILED ? null : binderId })}
          disabled={disabled}
          testID="item-binder"
        />
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {!binder
            ? 'Unfiled cards show on their own when public.'
            : binder.visibility === 'PRIVATE'
              ? 'This binder is private: publish it to show its public cards.'
              : 'This binder is public.'}
        </Text>
      </SectionCard>

      <SectionCard title="Notes">
        <TextField
          label="Public notes"
          value={value.publicNotes}
          onChangeText={(publicNotes) => onChange({ publicNotes })}
          multiline
          maxLength={PUBLIC_NOTES_MAX}
          hint={`Shown to collectors with the card. ${value.publicNotes.length} / ${PUBLIC_NOTES_MAX}`}
          error={errors.publicNotes}
          editable={!disabled}
          testID="item-public-notes"
        />
        <TextField
          label="Private notes"
          value={value.notes}
          onChangeText={(notes) => onChange({ notes })}
          multiline
          maxLength={NOTES_MAX}
          hint="Only you can see these."
          error={errors.notes}
          editable={!disabled}
          testID="item-notes"
        />
      </SectionCard>
    </View>
  );
}

function visibilityHint(visibility: ItemFormValue['visibility']): string {
  switch (visibility) {
    case 'PRIVATE':
      return 'Private: prepare it now and publish it later. Only you can see it.';
    case 'PUBLIC':
      return 'Public: collectors of your region can find it once its binder (if any) is public.';
    default:
      return 'Temporarily public: visible for the time you choose, then private again.';
  }
}

const styles = StyleSheet.create({
  root: { gap: spacing[4] },
});

// apps/web-angular/src/app/features/inventory/editor/item-details-fields.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  linkedSignal,
} from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import type { BinderResponse, GameSchema } from '@orenji/api-client';
import { editionLabel, finishLabel, languageLabel } from '../../../shared/catalog/catalog-labels';
import {
  CURRENCIES,
  INVENTORY_AVAILABILITIES,
  TEMPORARY_DURATIONS,
  VISIBILITIES,
  VISIBILITY_INFO,
  conditionLabel,
  endsLabel,
} from '../../../shared/inventory/inventory-labels';
import { AVAILABILITIES } from '../../../shared/ui/availability-chip/availability';
import { ItemForm, KEEP_END, PUBLIC_NOTES_MAX, NOTES_MAX, itemFieldError } from '../data/item-form';

/** Options of a schema list, keeping the current value even if the schema does not list it. */
function withCurrent(options: readonly string[] | undefined, current: string): string[] {
  const list = [...(options ?? [])];
  if (current && !list.includes(current)) {
    list.unshift(current);
  }
  return list;
}

/**
 * Every editable field of an inventory item (add dialog and edit panel): copies, condition,
 * language, edition, finish, availability, price and currency, offers, visibility with the
 * temporary duration, binder, public and private notes. Inline validation messages.
 */
@Component({
  selector: 'app-item-details-fields',
  imports: [
    ReactiveFormsModule,
    MatButtonToggleModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
  ],
  template: `
    @let f = form();
    <div class="idf" [formGroup]="f">
      <fieldset class="idf__group">
        <legend class="idf__legend">Card</legend>
        <div class="idf__grid">
          <mat-form-field appearance="outline">
            <mat-label>Quantity</mat-label>
            <input
              matInput
              type="number"
              inputmode="numeric"
              min="1"
              max="9999"
              step="1"
              formControlName="quantity"
            />
            @if (f.controls.quantity.invalid) {
              <mat-error>{{ error('quantity') }}</mat-error>
            }
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Condition</mat-label>
            <mat-select formControlName="condition">
              @for (value of conditions(); track value) {
                <mat-option [value]="value">{{ conditionText(value) }}</mat-option>
              }
            </mat-select>
            @if (f.controls.condition.invalid) {
              <mat-error>{{ error('condition') }}</mat-error>
            }
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Language</mat-label>
            <mat-select formControlName="language">
              @for (value of languages(); track value) {
                <mat-option [value]="value">{{ languageText(value) }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Edition</mat-label>
            <mat-select formControlName="edition">
              @for (value of editions(); track value) {
                <mat-option [value]="value">{{ editionText(value) }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Finish</mat-label>
            <mat-select formControlName="finish">
              @for (value of finishes(); track value) {
                <mat-option [value]="value">{{ finishText(value) }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>
      </fieldset>

      <fieldset class="idf__group">
        <legend class="idf__legend">Listing</legend>
        <div class="idf__grid">
          <mat-form-field appearance="outline">
            <mat-label>Availability</mat-label>
            <mat-select formControlName="availability">
              @for (value of availabilities; track value) {
                <mat-option [value]="value">{{ availabilityInfo[value].label }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Asking price</mat-label>
            <input
              matInput
              type="number"
              inputmode="decimal"
              min="0"
              step="0.01"
              formControlName="askingPrice"
            />
            <mat-hint>Optional</mat-hint>
            @if (f.controls.askingPrice.invalid) {
              <mat-error>{{ error('askingPrice') }}</mat-error>
            }
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Currency</mat-label>
            <mat-select formControlName="currency">
              @for (value of currencies(); track value) {
                <mat-option [value]="value">{{ value }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>
        <mat-slide-toggle formControlName="acceptsOffers">Accepts offers</mat-slide-toggle>
      </fieldset>

      <fieldset class="idf__group">
        <legend class="idf__legend">Visibility</legend>
        <mat-button-toggle-group
          class="idf__visibility"
          formControlName="visibility"
          aria-label="Visibility"
          hideSingleSelectionIndicator
        >
          @for (value of visibilities; track value) {
            <mat-button-toggle [value]="value">
              <mat-icon aria-hidden="true">{{ visibilityInfo[value].icon }}</mat-icon>
              {{ visibilityInfo[value].label }}
            </mat-button-toggle>
          }
        </mat-button-toggle-group>
        <p class="idf__hint">{{ visibilityHint() }}</p>
        <div class="idf__grid idf__grid--wide">
          @if (visibility() === 'TEMPORARILY_PUBLIC') {
            <mat-form-field appearance="outline" subscriptSizing="dynamic">
              <mat-label>Public for</mat-label>
              <mat-select formControlName="duration">
                @if (currentEnd(); as ends) {
                  <mat-option [value]="keepEnd">Keep current end ({{ ends }})</mat-option>
                }
                @for (option of durations; track option.value) {
                  <mat-option [value]="option.value">{{ option.label }}</mat-option>
                }
              </mat-select>
              <mat-hint>Then private again automatically.</mat-hint>
            </mat-form-field>
          }
          <mat-form-field appearance="outline" subscriptSizing="dynamic">
            <mat-label>Binder</mat-label>
            <mat-select formControlName="binderId">
              <mat-option [value]="null">No binder (unfiled)</mat-option>
              @for (binder of binders(); track binder.id) {
                <mat-option [value]="binder.id">{{ binder.name }}</mat-option>
              }
            </mat-select>
            <mat-hint>{{ binderHint() }}</mat-hint>
          </mat-form-field>
        </div>
      </fieldset>

      <fieldset class="idf__group">
        <legend class="idf__legend">Notes</legend>
        <mat-form-field appearance="outline">
          <mat-label>Public notes</mat-label>
          <textarea
            matInput
            rows="2"
            formControlName="publicNotes"
            [maxlength]="publicNotesMax"
          ></textarea>
          <mat-hint>Shown to collectors with the card.</mat-hint>
          <mat-hint align="end"
            >{{ f.controls.publicNotes.value.length }} / {{ publicNotesMax }}</mat-hint
          >
          @if (f.controls.publicNotes.invalid) {
            <mat-error>{{ error('publicNotes') }}</mat-error>
          }
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Private notes</mat-label>
          <mat-icon matPrefix aria-hidden="true">lock</mat-icon>
          <textarea matInput rows="2" formControlName="notes" [maxlength]="notesMax"></textarea>
          <mat-hint>Only you can see these.</mat-hint>
          @if (f.controls.notes.invalid) {
            <mat-error>{{ error('notes') }}</mat-error>
          }
        </mat-form-field>
      </fieldset>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .idf {
      display: flex;
      flex-direction: column;
      gap: var(--spacing-4);
    }
    .idf__group {
      display: flex;
      flex-direction: column;
      gap: var(--spacing-2);
      min-width: 0;
      margin: 0;
      padding: 0;
      border: 0;
    }
    .idf__legend {
      margin-bottom: var(--spacing-2);
      padding: 0;
      font-family: var(--font-display);
      font-size: var(--font-size-md);
      font-weight: var(--font-weight-semibold);
    }
    .idf__grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
      gap: 0 var(--spacing-3);
    }
    .idf__grid--wide {
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: var(--spacing-3);
    }
    .idf__visibility {
      align-self: flex-start;
      max-width: 100%;
      overflow-x: auto;
    }
    .idf__visibility mat-icon {
      width: 18px;
      height: 18px;
      margin-right: 4px;
      font-size: 18px;
      vertical-align: -4px;
    }
    .idf__hint {
      margin: 0 0 var(--spacing-2);
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ItemDetailsFieldsComponent {
  readonly form = input.required<ItemForm>();
  readonly schema = input<GameSchema | null>(null);
  readonly binders = input<readonly BinderResponse[]>([]);
  /** End of the running temporary publication (edit panel). */
  readonly publicUntil = input<string | null | undefined>(null);

  protected readonly keepEnd = KEEP_END;
  protected readonly visibilities = VISIBILITIES;
  protected readonly visibilityInfo = VISIBILITY_INFO;
  protected readonly availabilities = INVENTORY_AVAILABILITIES;
  protected readonly availabilityInfo = AVAILABILITIES;
  protected readonly durations = TEMPORARY_DURATIONS;
  protected readonly notesMax = NOTES_MAX;
  protected readonly publicNotesMax = PUBLIC_NOTES_MAX;
  protected readonly conditionText = conditionLabel;
  protected readonly languageText = languageLabel;
  protected readonly editionText = editionLabel;
  protected readonly finishText = finishLabel;

  /** The form's current value as a signal (the controls drive the hints below). */
  private readonly value = linkedSignal(() => this.form().getRawValue());
  protected readonly visibility = computed(() => this.value().visibility);
  protected readonly binderId = computed(() => this.value().binderId);

  protected readonly conditions = computed(() =>
    withCurrent(this.schema()?.conditions, this.form().controls.condition.value),
  );
  protected readonly languages = computed(() =>
    withCurrent(this.schema()?.languages, this.form().controls.language.value),
  );
  protected readonly editions = computed(() =>
    withCurrent(this.schema()?.editions, this.form().controls.edition.value),
  );
  protected readonly finishes = computed(() =>
    withCurrent(this.schema()?.finishes, this.form().controls.finish.value),
  );
  protected readonly currencies = computed(() =>
    withCurrent(CURRENCIES, this.form().controls.currency.value),
  );
  protected readonly currentEnd = computed(() => {
    const until = this.publicUntil();
    return until && Date.parse(until) > Date.now() ? endsLabel(until) : null;
  });
  protected readonly visibilityHint = computed(() => {
    switch (this.visibility()) {
      case 'PRIVATE':
        return 'Private: prepare it now and publish it later. Only you can see it.';
      case 'PUBLIC':
        return 'Public: collectors of your region can find it once its binder (if any) is public.';
      default:
        return 'Temporarily public: visible for the time you choose, then private again.';
    }
  });
  protected readonly binderHint = computed(() => {
    const id = this.binderId();
    const binder = id ? this.binders().find((candidate) => candidate.id === id) : null;
    if (!binder) {
      return 'Unfiled cards show on their own when public.';
    }
    return binder.visibility === 'PRIVATE'
      ? 'This binder is private: publish it to show its public cards.'
      : 'This binder is public.';
  });

  constructor() {
    effect((onCleanup) => {
      const form = this.form();
      const subscription = form.valueChanges.subscribe(() => this.value.set(form.getRawValue()));
      onCleanup(() => subscription.unsubscribe());
    });
  }

  protected error(
    field: 'quantity' | 'askingPrice' | 'notes' | 'publicNotes' | 'condition',
  ): string | null {
    return itemFieldError(field, this.form().controls[field].errors);
  }
}
