// apps/mobile/src/features/notifications/NotificationEntry.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter, type Href } from 'expo-router';
import { useCallback } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { useMarkNotificationRead } from '@/src/api/hooks/notificationCentre';
import type { NotificationResponse } from '@/src/api/types';
import { CardImage } from '@/src/components/ui/CardImage';
import { useSnackbar } from '@/src/components/ui/Snackbar';
import { relativeTime } from '@/src/lib/relativeTime';
import { fontWeight, spacing, textStyle, useTheme, type Palette } from '@/src/theme';

import {
  isUnread,
  notificationCard,
  notificationKind,
  notificationTarget,
  type NotificationTone,
} from './notificationKinds';

function toneColor(tone: NotificationTone, palette: Palette): string {
  switch (tone) {
    case 'match':
      return palette.primary;
    case 'message':
      return palette.accent;
    case 'offer':
      return palette.availability.offers;
    case 'trade':
      return palette.info;
    case 'warning':
      return palette.warning;
    default:
      return palette.textMuted;
  }
}

/**
 * One notification as content (the web's `app-notification-entry`): the card it is about (or a
 * tinted icon per type), category and time, title, body and an unread dot.
 */
export function NotificationEntry({ notification }: { notification: NotificationResponse }) {
  const { palette } = useTheme();
  const kind = notificationKind(notification);
  const card = notificationCard(notification);
  const color = toneColor(kind.tone, palette);
  const unread = isUnread(notification);
  return (
    <View style={styles.entry}>
      {card ? (
        <View testID="notification-card-image">
          <CardImage src={card.imageUrl} alt={card.name} game={card.game} size="xs" />
          <View style={[styles.badge, { backgroundColor: color }]}>
            <MaterialCommunityIcons name={kind.icon} size={12} color="#FFFFFF" />
          </View>
        </View>
      ) : (
        <View style={[styles.icon, { backgroundColor: palette.surfaceVariant }]}>
          <MaterialCommunityIcons name={kind.icon} size={22} color={color} />
        </View>
      )}
      <View style={styles.text}>
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          <Text style={[styles.strong, { color }]}>{kind.label}</Text> ·{' '}
          {relativeTime(notification.createdAt)}
        </Text>
        <Text style={[textStyle('md'), unread && styles.strong, { color: palette.ink }]}>
          {notification.title}
        </Text>
        <Text style={[textStyle('sm'), { color: palette.textMuted }]}>{notification.body}</Text>
      </View>
      {unread ? (
        <View
          testID="notification-unread-dot"
          accessibilityLabel="Unread"
          style={[styles.dot, { backgroundColor: palette.primary }]}
        />
      ) : null}
    </View>
  );
}

/**
 * Opening a notification: it is marked read, then its screen opens (the deep link mapped to the
 * app), or a snackbar explains where to follow it when that screen arrives in a later stage.
 */
export function useOpenNotification() {
  const router = useRouter();
  const snackbar = useSnackbar();
  const markRead = useMarkNotificationRead();
  const mutate = markRead.mutate;
  return useCallback(
    (notification: NotificationResponse) => {
      if (isUnread(notification)) {
        mutate(notification);
      }
      const target = notificationTarget(notification);
      if (target.kind === 'route') {
        router.push(target.href as Href);
      } else {
        snackbar.show(target.note, { duration: 6000 });
      }
    },
    [mutate, router, snackbar]
  );
}

const styles = StyleSheet.create({
  entry: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', gap: spacing[3] },
  icon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    right: -6,
    bottom: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: { flex: 1, gap: 2 },
  strong: { fontWeight: fontWeight.semibold },
  dot: { width: 10, height: 10, borderRadius: 5, marginTop: 6 },
});

// apps/web-angular/src/app/core/notifications/notification-entry.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  input,
} from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import type { NotificationResponse } from '@orenji/api-client';
import { RelativeTimePipe } from '../../shared/pipes/relative-time.pipe';
import { isUnread, notificationCard, notificationKind } from './notification-kinds';
import { CardImageComponent } from '../../shared/ui/card-image/card-image.component';

/**
 * One notification as content (the bell menu wraps it in a menu item, the notifications page in a
 * link): a tinted icon per type, category and time, title, body and an unread dot.
 */
@Component({
  selector: 'app-notification-entry',
  imports: [CardImageComponent, MatIconModule, RelativeTimePipe],
  template: `
    @let n = notification();
    @if (card(); as card) {
      <span class="ne__card" data-testid="notification-card-image">
        <app-card-image size="xs" [src]="card.imageUrl" [alt]="card.name" [game]="card.game" />
        <span class="ne__badge" [attr.data-tone]="kind().tone" aria-hidden="true">
          <mat-icon>{{ kind().icon }}</mat-icon>
        </span>
      </span>
    } @else {
      <span class="ne__icon" [attr.data-tone]="kind().tone" aria-hidden="true">
        <mat-icon>{{ kind().icon }}</mat-icon>
      </span>
    }
    <span class="ne__text">
      <span class="ne__meta">
        <span class="ne__label">{{ kind().label }}</span>
        <span aria-hidden="true">·</span>
        <time [attr.datetime]="n.createdAt">{{ n.createdAt | relativeTime }}</time>
      </span>
      <span class="ne__title">{{ n.title }}</span>
      <span class="ne__body" [class.ne__body--clamp]="compact()">{{ n.body }}</span>
    </span>
    @if (unread()) {
      <span class="ne__dot" data-testid="notification-unread-dot" aria-hidden="true"></span>
      <span class="visually-hidden">Unread</span>
    }
  `,
  styles: `
    :host {
      display: flex;
      align-items: flex-start;
      gap: var(--spacing-3);
      width: 100%;
      min-width: 0;
      text-align: left;
    }
    .ne__icon {
      display: grid;
      flex: 0 0 auto;
      place-items: center;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      background: var(--ne-tone-bg, var(--color-surface-variant));
      color: var(--ne-tone, var(--color-text-muted));
    }
    .ne__icon mat-icon {
      margin: 0;
      font-size: 22px;
      width: 22px;
      height: 22px;
    }
    .ne__card {
      position: relative;
      flex: 0 0 auto;
      width: 40px;
    }
    .ne__card app-card-image {
      --card-image-width: 40px;
    }
    .ne__badge {
      position: absolute;
      right: -6px;
      bottom: -4px;
      display: grid;
      place-items: center;
      width: 22px;
      height: 22px;
      border: 2px solid var(--color-surface);
      border-radius: 50%;
      background: var(--ne-tone-bg, var(--color-surface-variant));
      color: var(--ne-tone, var(--color-text-muted));
    }
    .ne__badge mat-icon {
      margin: 0;
      font-size: 13px;
      width: 13px;
      height: 13px;
    }
    [data-tone='match'] {
      --ne-tone: var(--color-primary);
      --ne-tone-bg: var(--color-primary-container);
    }
    [data-tone='message'] {
      --ne-tone: var(--color-accent);
      --ne-tone-bg: var(--color-accent-container);
    }
    [data-tone='offer'],
    [data-tone='trade'] {
      --ne-tone: var(--color-success);
      --ne-tone-bg: color-mix(in srgb, var(--color-success) 14%, var(--color-surface));
    }
    .ne__icon[data-tone='warning'],
    .ne__badge[data-tone='warning'] {
      --ne-tone: var(--color-warning);
      --ne-tone-bg: color-mix(in srgb, var(--color-warning) 16%, var(--color-surface));
    }
    .ne__text {
      display: flex;
      flex: 1 1 auto;
      flex-direction: column;
      gap: 2px;
      min-width: 0;
    }
    .ne__meta {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .ne__label {
      font-weight: var(--font-weight-semibold);
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .ne__title {
      color: var(--color-ink);
      font-size: var(--font-size-sm);
      font-weight: var(--font-weight-semibold);
      line-height: 1.35;
    }
    .ne__body {
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
      line-height: 1.4;
    }
    .ne__body--clamp {
      display: -webkit-box;
      overflow: hidden;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
    }
    .ne__dot {
      flex: 0 0 auto;
      width: 10px;
      height: 10px;
      margin-top: 6px;
      border-radius: 50%;
      background: var(--color-primary);
      box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-primary) 20%, transparent);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NotificationEntryComponent {
  readonly notification = input.required<NotificationResponse>();
  /** Clamp the body to two lines (menu). */
  readonly compact = input(false, { transform: booleanAttribute });

  protected readonly kind = computed(() => notificationKind(this.notification()));
  /** The card the payload carries (wishlist alerts, offers), shown instead of the icon. */
  protected readonly card = computed(() => notificationCard(this.notification()));
  protected readonly unread = computed(() => isUnread(this.notification()));
}
