// apps/mobile/src/features/offers/OfferPartyCard.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import type { OfferParty } from '@/src/api/types';
import { Avatar } from '@/src/components/ui/Avatar';
import { ratingLabel } from '@/src/features/map/discovery';
import { formatDistanceBucket, isDistanceBucket } from '@/src/lib/formatDistanceBucket';
import { fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

/**
 * One party of an offer or trade (web: `app-offer-party-card`): avatar, role, name (opens the
 * profile), the region label and distance **bucket** when the collector is discoverable (never a
 * point) and the rating.
 */
export function OfferPartyCard({
  party,
  role,
  isYou = false,
  testID,
}: {
  party: OfferParty;
  role: string;
  isYou?: boolean;
  testID?: string;
}) {
  const { palette } = useTheme();
  const router = useRouter();
  const bucket = party.location?.distanceBucket;
  const place = party.location?.publicLabel ?? null;
  return (
    <Pressable
      accessibilityRole="link"
      accessibilityLabel={`${role}${isYou ? ' (you)' : ''}: ${party.displayName}. Opens their profile.`}
      onPress={() => router.push({ pathname: '/collectors/[id]', params: { id: party.handle } })}
      testID={testID}
      style={({ pressed }) => [
        styles.card,
        { borderColor: palette.border, backgroundColor: palette.surface },
        pressed && styles.pressed,
      ]}
    >
      <Avatar src={party.avatarUrl} name={party.displayName} size={40} />
      <View style={styles.body}>
        <Text style={[textStyle('xs'), styles.role, { color: palette.textMuted }]}>
          {role}
          {isYou ? ' · You' : ''}
        </Text>
        <Text style={[textStyle('md'), styles.name, { color: palette.ink }]}>
          {party.displayName}
        </Text>
        {place ? (
          <View style={styles.line}>
            <MaterialCommunityIcons
              name="map-marker-radius-outline"
              size={14}
              color={palette.textMuted}
            />
            <Text style={[textStyle('xs'), styles.grow, { color: palette.textMuted }]}>
              {place}
              {isDistanceBucket(bucket) ? ` · ${formatDistanceBucket(bucket)}` : ''}
            </Text>
          </View>
        ) : null}
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {ratingLabel(party.rating)}
        </Text>
      </View>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing[3],
  },
  body: { flex: 1, gap: 2 },
  role: { textTransform: 'uppercase', letterSpacing: 0.5 },
  name: { fontWeight: fontWeight.semibold },
  line: { flexDirection: 'row', alignItems: 'center', gap: spacing[1] },
  grow: { flex: 1 },
  pressed: { opacity: 0.8 },
});

// apps/web-angular/src/app/shared/offers/offer-party-card.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import type { OfferParty } from '@orenji/api-client';
import { ratingLabel } from '../discovery/discovery-labels';
import { distanceBucketLabel } from '../domain/location-labels';
import { StarRatingComponent } from '../ratings/star-rating.component';
import { AvatarComponent } from '../ui/avatar/avatar.component';

/**
 * One party of an offer or a trade: avatar, name (links to the profile), role, approximate place
 * (region label and distance bucket only, ADR 0004) and rating summary.
 */
@Component({
  selector: 'app-offer-party-card',
  imports: [RouterLink, MatIconModule, AvatarComponent, StarRatingComponent],
  template: `
    @let p = party();
    <article class="party" [attr.aria-label]="role() + ': ' + p.displayName">
      <app-avatar [src]="p.avatarUrl" [name]="p.displayName" [decorative]="true" />
      <div class="party__body">
        <p class="party__role">
          {{ role() }}
          @if (isYou()) {
            <span class="party__you">You</span>
          }
        </p>
        <a class="party__name" [routerLink]="['/collectors', p.handle]">{{ p.displayName }}</a>
        @if (p.location; as location) {
          <p class="party__place">
            <mat-icon aria-hidden="true">location_on</mat-icon>
            {{ location.publicLabel }}
            @if (distance(); as distance) {
              · {{ distance }}
            }
          </p>
        }
        <p class="party__rating">
          @if (p.rating.count > 0) {
            <app-star-rating size="sm" [value]="p.rating.average" />
          }
          <span>{{ rating() }}</span>
        </p>
      </div>
    </article>
  `,
  styles: `
    .party {
      display: flex;
      gap: var(--spacing-3);
      padding: var(--spacing-3);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      background: var(--color-surface);
    }
    .party__body {
      display: flex;
      flex-direction: column;
      gap: 2px;
      min-width: 0;
    }
    .party__role {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
      margin: 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-semibold);
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }
    .party__you {
      padding: 0 6px;
      border-radius: var(--radius-pill);
      background: var(--color-accent-container);
      color: var(--color-on-accent-container);
      letter-spacing: normal;
      text-transform: none;
    }
    .party__name {
      overflow: hidden;
      color: var(--color-ink);
      font-weight: var(--font-weight-semibold);
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .party__place,
    .party__rating {
      display: flex;
      align-items: center;
      gap: 4px;
      margin: 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .party__place mat-icon {
      width: 14px;
      height: 14px;
      font-size: 14px;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OfferPartyCardComponent {
  readonly party = input.required<OfferParty>();
  /** "Seller" / "Buyer". */
  readonly role = input('Collector');
  readonly isYou = input(false);

  protected readonly distance = computed(() =>
    distanceBucketLabel(this.party().location?.distanceBucket),
  );
  protected readonly rating = computed(() => ratingLabel(this.party().rating));
}
