// apps/mobile/src/features/wishlist/WishFields.tsx
import { StyleSheet, Text, View } from 'react-native';

import type { PrintingSummary, WishPriceTerm } from '@/src/api/types';
import { Checkbox } from '@/src/components/ui/FormControls';
import { SectionCard } from '@/src/components/ui/Layout';
import { SelectSheet } from '@/src/components/ui/SelectSheet';
import { TextField } from '@/src/components/ui/TextField';
import { spacing, textStyle, useTheme } from '@/src/theme';

import {
  WISH_NOTE_MAX,
  copyOptions,
  copyValue,
  noteLength,
  withCopy,
  type WishFormErrors,
  type WishFormValue,
} from './wishForm';
import { approximateAmount, marketPriceSource } from './wishlistLabels';

/** The terms to offer: the admin list, plus `current` when the list no longer has it (web twin). */
export function withCurrentTerm(
  terms: readonly WishPriceTerm[],
  current: string | null | undefined
): readonly WishPriceTerm[] {
  if (!current || terms.some((term) => term.label === current)) {
    return terms;
  }
  const match = /^([1-9]\d{0,2})% TCG(\+)?$/.exec(current);
  return match
    ? [...terms, { label: current, percent: Number(match[1]), orMore: !!match[2] }]
    : terms;
}

export interface WishFieldsProps {
  value: WishFormValue;
  onChange: (value: WishFormValue) => void;
  errors: WishFormErrors;
  printings: readonly PrintingSummary[];
  terms: readonly WishPriceTerm[];
  termsError?: boolean;
  disabled?: boolean;
}

/**
 * The wish form's fields (stage S2, web: `app-wish-fields` + the printing picker): the public
 * note first, "Near Mint only", at most one price term (with its approximate amount when one
 * printing with a market price is chosen) and which copy (a simple chooser: any printing, any
 * printing of one rarity, or one printing). Inline validation messages.
 */
export function WishFields({
  value,
  onChange,
  errors,
  printings,
  terms,
  termsError = false,
  disabled = false,
}: WishFieldsProps) {
  const { palette } = useTheme();
  const set = <K extends keyof WishFormValue>(key: K, next: WishFormValue[K]) =>
    onChange({ ...value, [key]: next });
  const printing = printings.find((candidate) => candidate.id === value.printingId) ?? null;
  const price = printing?.marketPrice ?? null;
  const source = marketPriceSource(price);

  return (
    <View style={styles.root} testID="wish-fields">
      <TextField
        label="Public note (optional)"
        value={value.note}
        onChangeText={(next) => set('note', next)}
        multiline
        maxLength={WISH_NOTE_MAX * 2}
        error={errors.note}
        hint={`Everyone who can see your wishlist sees this note. ${noteLength(value.note)} / ${WISH_NOTE_MAX}`}
        editable={!disabled}
        testID="wish-note"
      />
      <Checkbox
        label="Near Mint only"
        checked={value.nearMintOnly}
        onChange={(next) => set('nearMintOnly', next)}
        disabled={disabled}
        testID="wish-near-mint"
      />

      <SectionCard title="Price (optional, at most one)" testID="wish-terms">
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {source
            ? `Terms relative to the market price of this printing (${source}). Sellers see them; they never filter anything.`
            : 'Terms relative to the TCG market price of the copy you get. Sellers see them; they never filter anything.'}
        </Text>
        {withCurrentTerm(terms, value.priceTerm).map((term) => {
          const amount = approximateAmount(term, price);
          const label = amount ? `${term.label} ${amount}` : term.label;
          return (
            <Checkbox
              key={term.label}
              label={label}
              checked={value.priceTerm === term.label}
              onChange={(checked) =>
                set(
                  'priceTerm',
                  checked ? term.label : value.priceTerm === term.label ? '' : value.priceTerm
                )
              }
              disabled={disabled}
              testID={`wish-term-${term.percent}${term.orMore ? '-plus' : ''}`}
            />
          );
        })}
        {termsError && !terms.length ? (
          <Text accessibilityRole="alert" style={[textStyle('xs'), { color: palette.danger }]}>
            The price terms could not load. Try again later.
          </Text>
        ) : null}
        {errors.priceTerm ? (
          <Text accessibilityRole="alert" style={[textStyle('xs'), { color: palette.danger }]}>
            {errors.priceTerm}
          </Text>
        ) : null}
      </SectionCard>

      <SectionCard title="Which copy" testID="wish-copy-section">
        <SelectSheet
          label="Which copy"
          options={copyOptions(printings)}
          value={copyValue(value)}
          onChange={(next) => onChange(withCopy(value, next))}
          disabled={disabled}
          testID="wish-copy"
        />
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {value.printingId
            ? 'Only this printing.'
            : value.rarity
              ? `Any printing in ${value.rarity}.`
              : 'Any printing of the card.'}
        </Text>
        {errors.printingId || errors.rarity ? (
          <Text accessibilityRole="alert" style={[textStyle('xs'), { color: palette.danger }]}>
            {errors.printingId ?? errors.rarity}
          </Text>
        ) : null}
      </SectionCard>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { gap: spacing[4] },
});

// apps/web-angular/src/app/shared/wishlist/wish-fields.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  linkedSignal,
} from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatTooltipModule } from '@angular/material/tooltip';
import type { MarketPrice, WishPriceTerm } from '@orenji/api-client';
import { marketPriceInfo } from '../catalog/catalog-labels';
import { WISH_NOTE_MAX, WishForm, noteError, noteLength } from './wishlist-form';
import { approximateAmount } from './wishlist-labels';

/** The terms to offer: the admin list, plus `current` when the list no longer has it. */
export function withCurrentTerm(
  terms: readonly WishPriceTerm[],
  current: string | null | undefined,
): readonly WishPriceTerm[] {
  if (!current || terms.some((term) => term.label === current)) {
    return terms;
  }
  const match = /^([1-9]\d{0,2})% TCG(\+)?$/.exec(current);
  return match
    ? [...terms, { label: current, percent: Number(match[1]), orMore: !!match[2] }]
    : terms;
}

/**
 * The public part of a wish (add/edit dialog): the public note first (plain text, at most 280
 * characters, shown wherever the wish is visible), then the optional "Near Mint only" and price
 * term checkboxes. At most one price term: checking one clears the others. With one printing
 * chosen and a market price known, each term shows its approximate amount ("85% TCG ≈ 21.25 USD")
 * and the price's source and date; with "Any printing" only the term.
 */
@Component({
  selector: 'app-wish-fields',
  imports: [
    ReactiveFormsModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatTooltipModule,
  ],
  template: `
    @let f = form();
    <div class="wf" [formGroup]="f">
      <mat-form-field appearance="outline" class="wf__note">
        <mat-label>Public note (optional)</mat-label>
        <textarea
          matInput
          rows="2"
          formControlName="note"
          data-testid="wish-note"
          [attr.maxlength]="noteMax * 2"
        ></textarea>
        <mat-hint>Everyone who can see your wishlist sees this note.</mat-hint>
        <mat-hint align="end">{{ length() }} / {{ noteMax }}</mat-hint>
        @if (f.controls.note.invalid) {
          <mat-error>{{ error() }}</mat-error>
        }
      </mat-form-field>

      <mat-checkbox formControlName="nearMintOnly" data-testid="wish-near-mint">
        Near Mint only
      </mat-checkbox>

      <fieldset class="wf__terms" aria-describedby="wish-terms-hint">
        <legend class="wf__legend">Price (optional, at most one)</legend>
        <p class="wf__hint" id="wish-terms-hint">
          {{ termsHint() }}
          @if (priceInfo(); as info) {
            <span class="wf__source" [matTooltip]="info.detail" tabindex="0">
              <mat-icon aria-hidden="true">info</mat-icon>
              <span class="visually-hidden">{{ info.label }}: {{ info.detail }}</span>
            </span>
          }
        </p>
        @if (shownTerms().length) {
          <div class="wf__term-list">
            @for (term of shownTerms(); track term.label) {
              <mat-checkbox
                [checked]="selectedTerm() === term.label"
                (change)="toggleTerm(term.label, $event.checked)"
                [attr.data-testid]="'wish-term-' + term.label"
              >
                {{ term.label }}
                @if (amount(term); as approx) {
                  <span class="wf__amount">{{ approx }}</span>
                }
              </mat-checkbox>
            }
          </div>
        } @else if (termsError()) {
          <p class="wf__hint" role="alert">The price terms could not load. Try again later.</p>
        }
        @if (f.controls.priceTerm.errors?.['server']; as message) {
          <p class="wf__error" role="alert">{{ message }}</p>
        }
      </fieldset>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .wf {
      display: flex;
      flex-direction: column;
      gap: var(--spacing-2);
    }
    .wf__note {
      width: 100%;
    }
    .wf__terms {
      min-width: 0;
      margin: var(--spacing-2) 0 0;
      padding: 0;
      border: 0;
    }
    .wf__legend {
      padding: 0;
      font-size: var(--font-size-sm);
      font-weight: var(--font-weight-semibold);
    }
    .wf__hint {
      display: flex;
      align-items: center;
      gap: var(--spacing-1);
      margin: var(--spacing-1) 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
    }
    .wf__source {
      display: inline-flex;
      cursor: help;
    }
    .wf__source mat-icon {
      width: 18px;
      height: 18px;
      font-size: 18px;
    }
    .wf__term-list {
      display: flex;
      flex-wrap: wrap;
      gap: 0 var(--spacing-3);
    }
    .wf__amount {
      margin-left: 4px;
      color: var(--color-text-muted);
    }
    .wf__error {
      margin: var(--spacing-1) 0 0;
      color: var(--color-danger);
      font-size: var(--font-size-sm);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WishFieldsComponent {
  readonly form = input.required<WishForm>();
  /** The admin list of price terms. */
  readonly terms = input<readonly WishPriceTerm[]>([]);
  readonly termsError = input(false);
  /** Market price of the chosen printing; `null` for "any printing" or without a price. */
  readonly marketPrice = input<MarketPrice | null | undefined>(null);

  protected readonly noteMax = WISH_NOTE_MAX;

  /** The form's current value as a signal. */
  private readonly value = linkedSignal(() => this.form().getRawValue());
  protected readonly length = computed(() => noteLength(this.value().note));
  protected readonly selectedTerm = computed(() => this.value().priceTerm);
  /** The admin list, plus the wish's own term when the list no longer offers it (kept on edit). */
  protected readonly shownTerms = computed(() =>
    withCurrentTerm(this.terms(), this.selectedTerm()),
  );
  protected readonly priceInfo = computed(() => marketPriceInfo(this.marketPrice()));
  protected readonly termsHint = computed(() =>
    this.priceInfo()
      ? `Terms relative to the ${this.priceInfo()?.label.toLowerCase()} of this printing. Sellers see them; they never filter anything.`
      : 'Terms relative to the TCG market price of the copy you get. Sellers see them; they never filter anything.',
  );

  constructor() {
    effect((onCleanup) => {
      const form = this.form();
      this.value.set(form.getRawValue());
      const subscription = form.valueChanges.subscribe(() => this.value.set(form.getRawValue()));
      onCleanup(() => subscription.unsubscribe());
    });
  }

  protected amount(term: WishPriceTerm): string | null {
    return approximateAmount(term, this.marketPrice());
  }

  protected error(): string | null {
    return noteError(this.form().controls.note.errors);
  }

  protected toggleTerm(label: string, checked: boolean): void {
    const control = this.form().controls.priceTerm;
    control.setValue(checked ? label : control.value === label ? '' : control.value);
    control.markAsDirty();
  }
}
