// apps/mobile/src/features/messages/MessageBubble.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import type { MessageImage, MessageResponse } from '@/src/api/types';
import { safeCardImageUrl } from '@/src/lib/cardImages';
import { fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

import { OfferLinkCard, SharedLinkCard } from './LinkCards';

/** Largest photo side in a bubble (dp). */
const PHOTO_MAX = 240;

function timeLabel(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) {
    return '';
  }
  return new Intl.DateTimeFormat('en', { hour: 'numeric', minute: '2-digit' }).format(date);
}

/**
 * One message (the web's `app-message-bubble`): text, a shared card or binder (with an optional
 * caption), a photo (tap to view it full screen), an offer card, or a system line (offer and
 * trade updates carry the offer card too). Removed messages keep their place with a neutral note.
 */
export function MessageBubble({
  message,
  own,
  showTime,
}: {
  message: MessageResponse;
  own: boolean;
  showTime: boolean;
}) {
  const { palette } = useTheme();
  if (message.kind === 'SYSTEM') {
    return (
      <View style={styles.system} testID={`message-${message.id}`}>
        <Text style={[textStyle('sm'), styles.systemText, { color: palette.textMuted }]}>
          {message.body}
        </Text>
        {message.payload?.offer ? <OfferLinkCard offer={message.payload.offer} /> : null}
      </View>
    );
  }
  const removed = message.moderationState === 'REMOVED';
  const textColor = own ? palette.onPrimary : palette.ink;
  let attachment = null;
  if (!removed) {
    switch (message.kind) {
      case 'CARD_LINK':
        attachment = message.payload?.card ? <SharedLinkCard card={message.payload.card} /> : null;
        break;
      case 'BINDER_LINK':
        attachment = message.payload?.binder ? (
          <SharedLinkCard binder={message.payload.binder} />
        ) : null;
        break;
      case 'IMAGE':
        attachment = message.payload?.image ? <Photo image={message.payload.image} /> : null;
        break;
      case 'OFFER_LINK':
        attachment = message.payload?.offer ? (
          <OfferLinkCard offer={message.payload.offer} />
        ) : null;
        break;
      default:
        break;
    }
  }
  return (
    <View
      testID={`message-${message.id}`}
      style={[
        styles.bubble,
        own
          ? [styles.own, { backgroundColor: palette.primary }]
          : [styles.other, { backgroundColor: palette.surfaceVariant }],
        message.moderationState === 'FLAGGED' && { borderColor: palette.warning, borderWidth: 1 },
      ]}
    >
      {removed ? (
        <View style={styles.removed}>
          <MaterialCommunityIcons name="cancel" size={16} color={textColor} />
          <Text style={[textStyle('md'), styles.italic, { color: textColor }]}>
            This message was removed by moderation.
          </Text>
        </View>
      ) : (
        <>
          {attachment}
          {message.body ? (
            <Text selectable style={[textStyle('md'), { color: textColor }]}>
              {message.body}
            </Text>
          ) : null}
        </>
      )}
      {showTime ? (
        <Text style={[textStyle('xs'), styles.time, { color: textColor }]}>
          {timeLabel(message.createdAt)}
          {message.editedAt ? ' · edited' : ''}
        </Text>
      ) : null}
    </View>
  );
}

/** A photo of an IMAGE message: API media only (ADR 0015 rules), full screen on tap. */
function Photo({ image }: { image: MessageImage }) {
  const { palette } = useTheme();
  const insets = useSafeAreaInsets();
  const [open, setOpen] = useState(false);
  const [failed, setFailed] = useState(false);
  const url = safeCardImageUrl(image.url);
  const ratio = image.width > 0 && image.height > 0 ? image.width / image.height : 1;
  const width = ratio >= 1 ? PHOTO_MAX : Math.round(PHOTO_MAX * ratio);
  const height = ratio >= 1 ? Math.round(PHOTO_MAX / ratio) : PHOTO_MAX;
  if (!url || failed) {
    return (
      <View
        testID="message-photo-unavailable"
        style={[styles.photoMissing, { backgroundColor: palette.surface }]}
      >
        <MaterialCommunityIcons name="image-off-outline" size={22} color={palette.textMuted} />
        <Text style={[textStyle('sm'), { color: palette.textMuted }]}>Photo unavailable</Text>
      </View>
    );
  }
  return (
    <>
      <Pressable
        accessibilityRole="imagebutton"
        accessibilityLabel="Photo sent in the conversation. Opens it full screen."
        onPress={() => setOpen(true)}
        testID="message-photo"
      >
        <Image
          source={{ uri: url }}
          style={[styles.photo, { width, height }]}
          contentFit="cover"
          cachePolicy="memory-disk"
          accessible={false}
          onError={() => setFailed(true)}
        />
      </Pressable>
      <Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}>
        <View style={[styles.viewer, { paddingTop: insets.top, paddingBottom: insets.bottom }]}>
          <Image
            source={{ uri: url }}
            style={styles.viewerImage}
            contentFit="contain"
            accessible
            accessibilityLabel="Photo sent in the conversation"
          />
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Close the photo"
            onPress={() => setOpen(false)}
            style={[styles.viewerClose, { top: insets.top + spacing[2] }]}
            testID="message-photo-close"
          >
            <MaterialCommunityIcons name="close" size={26} color="#FFFFFF" />
          </Pressable>
        </View>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  bubble: {
    maxWidth: '85%',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    gap: spacing[2],
    borderRadius: 18,
  },
  own: { alignSelf: 'flex-end', borderBottomRightRadius: 6 },
  other: { alignSelf: 'flex-start', borderBottomLeftRadius: 6 },
  time: { alignSelf: 'flex-end', opacity: 0.75 },
  removed: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  italic: { fontStyle: 'italic' },
  system: { alignSelf: 'center', alignItems: 'stretch', gap: spacing[2], maxWidth: '95%' },
  systemText: { textAlign: 'center' },
  photo: { borderRadius: radius.md },
  photoMissing: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    padding: spacing[3],
    borderRadius: radius.md,
  },
  viewer: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.92)', justifyContent: 'center' },
  viewerImage: { flex: 1 },
  viewerClose: {
    position: 'absolute',
    right: spacing[3],
    padding: spacing[2],
    borderRadius: radius.pill,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  strong: { fontWeight: fontWeight.semibold },
});

// apps/web-angular/src/app/features/messages/thread/message-bubble.component.ts
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import type { MessageResponse } from '@orenji/api-client';
import { SharedLinkCardComponent } from '../../../shared/links/shared-link-card.component';
import { OfferLinkCardComponent } from '../../../shared/offers/offer-link-card.component';
import { MediaUrlPipe } from '../../../shared/pipes/media-url.pipe';

/**
 * One message: text, shared card or binder (with an optional caption), photo, offer card (links
 * to the offer page) or a system line (offer and trade updates carry the offer card too). Removed
 * messages keep their place with a neutral note.
 */
@Component({
  selector: 'app-message-bubble',
  imports: [DatePipe, MatIconModule, MediaUrlPipe, OfferLinkCardComponent, SharedLinkCardComponent],
  template: `
    @let m = message();
    @if (m.kind === 'SYSTEM') {
      <div class="system" data-testid="system-message">
        <p class="system__text">{{ m.body }}</p>
        @if (m.payload.offer; as offer) {
          <app-offer-link-card class="system__offer" [offer]="offer" />
        }
      </div>
    } @else {
      <div
        class="bubble"
        [class.bubble--own]="own()"
        [class.bubble--flagged]="m.moderationState === 'FLAGGED'"
      >
        @if (m.moderationState === 'REMOVED') {
          <p class="bubble__removed">
            <mat-icon aria-hidden="true">block</mat-icon>
            This message was removed by moderation.
          </p>
        } @else {
          @switch (m.kind) {
            @case ('CARD_LINK') {
              <app-shared-link-card class="bubble__link" [card]="m.payload.card" />
            }
            @case ('BINDER_LINK') {
              <app-shared-link-card class="bubble__link" [binder]="m.payload.binder" />
            }
            @case ('IMAGE') {
              @if (m.payload.image; as image) {
                <a
                  class="bubble__photo"
                  [href]="image.url | mediaUrl"
                  target="_blank"
                  rel="noopener"
                >
                  <img
                    [src]="image.url | mediaUrl"
                    [attr.width]="image.width"
                    [attr.height]="image.height"
                    alt="Photo sent in the conversation"
                    loading="lazy"
                  />
                </a>
              }
            }
            @case ('OFFER_LINK') {
              @if (m.payload.offer; as offer) {
                <app-offer-link-card class="bubble__link" [offer]="offer" />
              }
            }
          }
          @if (m.body) {
            <p class="bubble__text">{{ m.body }}</p>
          }
        }
        @if (showTime()) {
          <time class="bubble__time" [attr.datetime]="m.createdAt">
            {{ m.createdAt | date: 'shortTime' }}
            @if (m.editedAt) {
              · edited
            }
          </time>
        }
      </div>
    }
  `,
  styles: `
    :host {
      display: block;
      max-width: min(80%, 420px);
    }
    :host:has(.system) {
      max-width: min(100%, 460px);
      margin-inline: auto;
    }
    .system {
      display: flex;
      flex-direction: column;
      align-items: stretch;
      gap: var(--spacing-2);
    }
    .system__text {
      margin: 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
      text-align: center;
    }
    .bubble {
      display: flex;
      flex-direction: column;
      gap: var(--spacing-2);
      padding: var(--spacing-2) var(--spacing-3);
      border-radius: 18px 18px 18px 6px;
      background: var(--color-surface-variant);
      color: var(--color-ink);
      animation: bubble-in var(--motion-duration-base) var(--motion-easing-standard);
    }
    .bubble--own {
      border-radius: 18px 18px 6px 18px;
      background: var(--color-primary);
      color: var(--color-on-primary);
    }
    .bubble--flagged {
      outline: 1px dashed var(--color-warning);
    }
    .bubble__text {
      margin: 0;
      overflow-wrap: anywhere;
      white-space: pre-wrap;
    }
    .bubble__link {
      color: var(--color-ink);
    }
    .bubble__photo img {
      display: block;
      width: 100%;
      max-width: 280px;
      height: auto;
      max-height: 320px;
      border-radius: var(--radius-md);
      object-fit: cover;
    }
    .bubble__removed {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
      margin: 0;
      font-style: italic;
    }
    .bubble__time {
      align-self: flex-end;
      font-size: var(--font-size-xs);
      opacity: 0.75;
    }
    @keyframes bubble-in {
      from {
        opacity: 0;
        transform: translateY(4px);
      }
    }
    @media (prefers-reduced-motion: reduce) {
      .bubble {
        animation: none;
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MessageBubbleComponent {
  readonly message = input.required<MessageResponse>();
  readonly own = input(false);
  /** Last message of a run: carries its time. */
  readonly showTime = input(true);
}
