// apps/mobile/src/features/disputes/EvidenceList.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, View } from 'react-native';

import { useEvidencePhoto } from '@/src/api/hooks/payments';
import type { DisputeEvidence } from '@/src/api/types';
import { evidenceKindInfo, fileSize } from '@/src/features/payments/paymentLabels';
import { formatDateTime } from '@/src/lib/dates';
import { fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

export interface EvidenceView {
  item: DisputeEvidence;
  kind: string;
  who: string;
  mine: boolean;
  /** An https tracking link (TRACKING evidence), never anything else. */
  link: string | null;
}

/** Evidence in words: its kind, who added it ("You", a party's name or OrenjiTrade). */
export function evidenceViews(
  evidence: readonly DisputeEvidence[],
  viewer: string | null | undefined,
  names: { BUYER: string; SELLER: string }
): EvidenceView[] {
  return evidence.map((item) => {
    const mine = !!viewer && item.role === viewer;
    const who = mine
      ? 'You'
      : item.role === 'BUYER'
        ? names.BUYER
        : item.role === 'SELLER'
          ? names.SELLER
          : 'OrenjiTrade';
    const link = item.url && /^https:\/\//i.test(item.url) ? item.url : null;
    return { item, kind: evidenceKindInfo(item.kind).label, who, mine, link };
  });
}

/** A photo of IMAGE evidence, loaded through the authenticated file route. */
function EvidencePhoto({
  disputeId,
  item,
  who,
}: {
  disputeId: string;
  item: DisputeEvidence;
  who: string;
}) {
  const { palette } = useTheme();
  const photo = useEvidencePhoto(disputeId, item.id);
  if (photo.data) {
    return (
      <Image
        source={{ uri: photo.data }}
        style={styles.photo}
        contentFit="contain"
        cachePolicy="none"
        accessibilityLabel={`Photo from ${who}`}
        testID="evidence-image"
      />
    );
  }
  if (photo.error) {
    return (
      <Text style={[textStyle('sm'), { color: palette.textMuted }]} testID="evidence-image-error">
        The photo could not load.
      </Text>
    );
  }
  return <ActivityIndicator accessibilityLabel="Loading the photo" color={palette.primary} />;
}

/**
 * The evidence of a dispute (web: `app-evidence-list`): each piece with its kind, who added it
 * and when; photos (fetched with the ID token, never through a public URL), PDF documents by
 * name and size, statements and tracking links.
 */
export function EvidenceList({
  disputeId,
  evidence,
  viewer,
  names,
}: {
  disputeId: string;
  evidence: readonly DisputeEvidence[];
  viewer: string | null | undefined;
  names: { BUYER: string; SELLER: string };
}) {
  const { palette } = useTheme();
  const views = evidenceViews(evidence, viewer, names);
  if (views.length === 0) {
    return (
      <Text style={[textStyle('sm'), { color: palette.textMuted }]} testID="evidence-empty">
        No evidence yet.
      </Text>
    );
  }
  return (
    <View style={styles.list} accessibilityLabel="Evidence">
      {views.map((view) => (
        <View
          key={view.item.id}
          testID="evidence-item"
          style={[
            styles.item,
            {
              backgroundColor: view.mine ? palette.surfaceVariant : palette.surface,
              borderColor: palette.border,
            },
          ]}
        >
          <View style={styles.head}>
            <MaterialCommunityIcons
              name={evidenceKindInfo(view.item.kind).icon}
              size={16}
              color={palette.textMuted}
            />
            <Text style={[textStyle('sm'), styles.strong, { color: palette.ink }]}>
              {view.kind}
            </Text>
            <Text style={[textStyle('xs'), styles.grow, { color: palette.textMuted }]}>
              {view.who} · {formatDateTime(view.item.createdAt)}
            </Text>
          </View>
          {view.item.kind === 'IMAGE' ? (
            <EvidencePhoto disputeId={disputeId} item={view.item} who={view.who} />
          ) : null}
          {view.item.kind === 'DOCUMENT' ? (
            <Text style={[textStyle('sm'), { color: palette.ink }]} testID="evidence-document">
              PDF document{view.item.sizeBytes ? ` (${fileSize(view.item.sizeBytes)})` : ''} — open
              it on orenjitrade.com
            </Text>
          ) : null}
          {view.item.body ? (
            <Text style={[textStyle('sm'), { color: palette.ink }]} testID="evidence-body">
              {view.item.body}
            </Text>
          ) : null}
          {view.link ? (
            <Pressable
              accessibilityRole="link"
              onPress={() => void Linking.openURL(view.link ?? '')}
              style={styles.head}
            >
              <MaterialCommunityIcons name="open-in-new" size={16} color={palette.accent} />
              <Text style={[textStyle('sm'), styles.link, { color: palette.accent }]}>
                Follow the tracking
              </Text>
            </Pressable>
          ) : null}
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  list: { gap: spacing[2] },
  item: { borderWidth: 1, borderRadius: radius.md, padding: spacing[3], gap: spacing[2] },
  head: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  grow: { flex: 1 },
  strong: { fontWeight: fontWeight.semibold },
  link: { textDecorationLine: 'underline' },
  photo: { width: '100%', height: 220, borderRadius: radius.sm },
});

// apps/web-angular/src/app/shared/payments/evidence-list.component.ts
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import type { DisputeEvidence } from '@orenji/api-client';
import { EvidenceFilesService } from './evidence-files.service';
import { evidenceKindInfo, fileSize } from './payment-labels';

interface EvidenceView {
  item: DisputeEvidence;
  icon: string;
  kind: string;
  who: string;
  mine: boolean;
  link: string | null;
}

/**
 * Evidence of both parties, oldest first: statements and tracking as text (tracking links only
 * when https), photos as previews loaded through the authenticated file route, PDF documents as
 * downloads. Files are never public URLs.
 */
@Component({
  selector: 'app-evidence-list',
  imports: [DatePipe, MatButtonModule, MatIconModule, MatProgressSpinnerModule],
  providers: [EvidenceFilesService],
  template: `
    @if (views().length === 0) {
      <p class="ev__empty">No evidence yet.</p>
    } @else {
      <ul class="ev" aria-label="Evidence">
        @for (view of views(); track view.item.id) {
          <li class="ev__item" [class.ev__item--mine]="view.mine" data-testid="evidence-item">
            <header class="ev__head">
              <span class="ev__kind">
                <mat-icon aria-hidden="true">{{ view.icon }}</mat-icon>
                {{ view.kind }}
              </span>
              <span class="ev__who">
                {{ view.who }} ·
                <time [attr.datetime]="view.item.createdAt">{{
                  view.item.createdAt | date: 'MMM d, h:mm a'
                }}</time>
              </span>
            </header>
            @switch (view.item.kind) {
              @case ('IMAGE') {
                @let preview = previewOf(view.item)();
                <div class="ev__image">
                  @if (preview.state === 'ready') {
                    <a [href]="preview.url" target="_blank" rel="noopener">
                      <img
                        [src]="preview.url"
                        [alt]="'Photo from ' + view.who"
                        loading="lazy"
                        data-testid="evidence-image"
                      />
                    </a>
                  } @else if (preview.state === 'error') {
                    <p class="ev__muted">The photo could not load.</p>
                  } @else {
                    <mat-spinner diameter="24" aria-label="Loading the photo" />
                  }
                </div>
              }
              @case ('DOCUMENT') {
                <button
                  matButton="tonal"
                  type="button"
                  class="ev__doc"
                  [disabled]="downloading() === view.item.id"
                  (click)="download(view.item)"
                >
                  <mat-icon aria-hidden="true">download</mat-icon>
                  Download PDF
                  @if (view.item.sizeBytes) {
                    ({{ size(view.item.sizeBytes) }})
                  }
                </button>
              }
            }
            @if (view.item.body) {
              <p class="ev__body">{{ view.item.body }}</p>
            }
            @if (view.link) {
              <a class="ev__link" [href]="view.link" target="_blank" rel="noopener noreferrer">
                <mat-icon aria-hidden="true">open_in_new</mat-icon>
                Follow the tracking
              </a>
            }
          </li>
        }
      </ul>
    }
  `,
  styles: `
    .ev {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: var(--spacing-3);
      margin: 0;
      padding: 0;
      list-style: none;
    }
    .ev__empty,
    .ev__muted {
      margin: 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
    }
    .ev__item {
      display: flex;
      flex-direction: column;
      gap: var(--spacing-2);
      padding: var(--spacing-3);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);
      background: var(--color-surface);
      animation: ev-in var(--motion-duration-base) var(--motion-easing-standard);
    }
    .ev__item--mine {
      border-color: color-mix(in srgb, var(--color-primary) 35%, var(--color-border));
    }
    .ev__head {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .ev__kind {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      color: var(--color-ink);
      font-weight: var(--font-weight-semibold);
    }
    .ev__kind mat-icon {
      width: 18px;
      height: 18px;
      font-size: 18px;
    }
    .ev__who {
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .ev__image {
      display: grid;
      place-items: center;
      min-height: 120px;
      overflow: hidden;
      border-radius: var(--radius-sm);
      background: var(--color-surface-variant);
    }
    .ev__image img {
      display: block;
      width: 100%;
      max-height: 220px;
      object-fit: cover;
    }
    .ev__body {
      margin: 0;
      font-size: var(--font-size-sm);
      white-space: pre-line;
      overflow-wrap: anywhere;
    }
    .ev__doc {
      align-self: flex-start;
    }
    .ev__link {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      font-size: var(--font-size-sm);
    }
    .ev__link mat-icon {
      width: 16px;
      height: 16px;
      font-size: 16px;
    }
    @keyframes ev-in {
      from {
        opacity: 0;
        transform: translateY(4px);
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EvidenceListComponent {
  private readonly files = inject(EvidenceFilesService);

  readonly disputeId = input.required<string>();
  readonly evidence = input.required<readonly DisputeEvidence[]>();
  /** The reader's side (`null` for admins). */
  readonly viewer = input<string | null>(null);
  readonly buyerName = input.required<string>();
  readonly sellerName = input.required<string>();

  protected readonly downloading = signal<string | null>(null);
  protected readonly size = fileSize;
  protected readonly views = computed<EvidenceView[]>(() =>
    this.evidence().map((item) => {
      const info = evidenceKindInfo(item.kind);
      const mine = !!this.viewer() && item.role === this.viewer();
      const who = mine
        ? 'You'
        : item.role === 'BUYER'
          ? this.buyerName()
          : item.role === 'SELLER'
            ? this.sellerName()
            : 'OrenjiTrade';
      const link = item.url && /^https:\/\//i.test(item.url) ? item.url : null;
      return { item, icon: info.icon, kind: info.label, who, mine, link };
    }),
  );

  protected previewOf(item: DisputeEvidence) {
    return this.files.preview(this.disputeId(), item);
  }

  protected async download(item: DisputeEvidence): Promise<void> {
    this.downloading.set(item.id);
    await this.files.download(this.disputeId(), item);
    this.downloading.set(null);
  }
}
