// apps/mobile/src/features/offers/OfferActionBar.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';

import { Button } from '@/src/components/ui/Button';
import { fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

import type { OfferActionName } from './offerLabels';

/**
 * "Your answer" (web: `app-offer-action-bar`): whose turn it is, and only the answers the API
 * allows right now (`allowedActions`): Accept, Counter, Decline (the party whose turn it is),
 * Withdraw (the buyer while OPEN), plus Message the other collector.
 */
export function OfferActionBar({
  allowedActions,
  busy,
  yourTurn,
  waiting,
  otherName,
  messaging,
  onAccept,
  onCounter,
  onDecline,
  onWithdraw,
  onMessage,
}: {
  allowedActions: readonly string[];
  busy: OfferActionName | null;
  yourTurn: boolean;
  waiting: boolean;
  otherName: string;
  messaging: boolean;
  onAccept: () => void;
  onCounter: () => void;
  onDecline: () => void;
  onWithdraw: () => void;
  onMessage: () => void;
}) {
  const { palette } = useTheme();
  const can = (action: OfferActionName) => allowedActions.includes(action);
  const title = yourTurn
    ? 'Your turn to answer'
    : waiting
      ? `Waiting for ${otherName}`
      : 'This negotiation is closed';
  const hint = yourTurn
    ? 'Accept to open a trade, counter with other terms, or decline.'
    : waiting
      ? `You will be notified as soon as ${otherName} answers.`
      : null;
  return (
    <View
      testID="offer-action-bar"
      style={[
        styles.bar,
        {
          borderColor: yourTurn ? palette.primary : palette.border,
          backgroundColor: yourTurn ? palette.primaryContainer : palette.surface,
        },
      ]}
    >
      <View style={styles.head}>
        <MaterialCommunityIcons
          name={yourTurn ? 'bell-ring-outline' : waiting ? 'timer-sand' : 'lock-clock'}
          size={20}
          color={yourTurn ? palette.onPrimaryContainer : palette.textMuted}
        />
        <Text
          testID="offer-turn"
          accessibilityRole="header"
          style={[
            textStyle('md'),
            styles.title,
            { color: yourTurn ? palette.onPrimaryContainer : palette.ink },
          ]}
        >
          {title}
        </Text>
      </View>
      {hint ? (
        <Text
          style={[
            textStyle('sm'),
            { color: yourTurn ? palette.onPrimaryContainer : palette.textMuted },
          ]}
        >
          {hint}
        </Text>
      ) : null}
      <View style={styles.actions}>
        {can('ACCEPT') ? (
          <Button
            label="Accept"
            icon="handshake"
            loading={busy === 'ACCEPT'}
            loadingLabel="Accepting…"
            disabled={!!busy}
            onPress={onAccept}
            testID="offer-accept"
          />
        ) : null}
        {can('COUNTER') ? (
          <Button
            label="Counter"
            icon="swap-horizontal"
            variant="secondary"
            disabled={!!busy}
            onPress={onCounter}
            testID="offer-counter"
          />
        ) : null}
        {can('DECLINE') ? (
          <Button
            label="Decline"
            icon="minus-circle-outline"
            variant="ghost"
            loading={busy === 'DECLINE'}
            loadingLabel="Declining…"
            disabled={!!busy}
            onPress={onDecline}
            testID="offer-decline"
          />
        ) : null}
        {can('CANCEL') ? (
          <Button
            label="Withdraw offer"
            icon="undo"
            variant="ghost"
            loading={busy === 'CANCEL'}
            loadingLabel="Withdrawing…"
            disabled={!!busy}
            onPress={onWithdraw}
            testID="offer-withdraw"
          />
        ) : null}
        <Button
          label={`Message ${otherName}`}
          icon="message-text-outline"
          variant="ghost"
          loading={messaging}
          loadingLabel="Opening…"
          onPress={onMessage}
          testID="offer-message-other"
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  bar: { borderWidth: 1, borderRadius: radius.md, padding: spacing[3], gap: spacing[2] },
  head: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  title: { fontWeight: fontWeight.semibold, flex: 1 },
  actions: { gap: spacing[2] },
});

// apps/web-angular/src/app/features/offers/detail/offer-action-bar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import type { OfferAction } from '../../../shared/offers/offer-labels';

/**
 * The answers to a proposal, only those the API allows the viewer now (`allowedActions`): Accept,
 * Counter, Decline for the party whose turn it is, Withdraw for the buyer while the offer is
 * OPEN. Otherwise it says whom the offer waits for. "Message" opens the pair conversation.
 */
@Component({
  selector: 'app-offer-action-bar',
  imports: [MatButtonModule, MatIconModule],
  template: `
    <section class="bar" [class.bar--turn]="yourTurn()" aria-label="Your answer">
      <div class="bar__text">
        @if (yourTurn()) {
          <p class="bar__title">
            <mat-icon aria-hidden="true">notifications_active</mat-icon>
            Your turn to answer
          </p>
          <p class="bar__hint">Accept to open a trade, counter with other terms, or decline.</p>
        } @else if (waiting()) {
          <p class="bar__title">
            <mat-icon aria-hidden="true">hourglass_top</mat-icon>
            Waiting for {{ otherName() }}
          </p>
          <p class="bar__hint">You will be notified as soon as {{ otherName() }} answers.</p>
        } @else {
          <p class="bar__title">
            <mat-icon aria-hidden="true">lock_clock</mat-icon>
            This negotiation is closed
          </p>
        }
      </div>
      <div class="bar__actions">
        @if (can('ACCEPT')) {
          <button
            matButton="filled"
            type="button"
            [disabled]="!!busy()"
            (click)="acceptRequested.emit()"
          >
            <mat-icon aria-hidden="true">handshake</mat-icon>
            {{ busy() === 'ACCEPT' ? 'Accepting…' : 'Accept' }}
          </button>
        }
        @if (can('COUNTER')) {
          <button
            matButton="outlined"
            type="button"
            [disabled]="!!busy()"
            (click)="counterRequested.emit()"
          >
            <mat-icon aria-hidden="true">swap_horiz</mat-icon>
            Counter
          </button>
        }
        @if (can('DECLINE')) {
          <button
            matButton
            type="button"
            class="bar__danger"
            [disabled]="!!busy()"
            (click)="declineRequested.emit()"
          >
            <mat-icon aria-hidden="true">do_not_disturb_on</mat-icon>
            {{ busy() === 'DECLINE' ? 'Declining…' : 'Decline' }}
          </button>
        }
        @if (can('CANCEL')) {
          <button
            matButton
            type="button"
            class="bar__danger"
            [disabled]="!!busy()"
            (click)="withdrawRequested.emit()"
          >
            <mat-icon aria-hidden="true">undo</mat-icon>
            {{ busy() === 'CANCEL' ? 'Withdrawing…' : 'Withdraw offer' }}
          </button>
        }
        <button matButton type="button" [disabled]="messaging()" (click)="messageRequested.emit()">
          <mat-icon aria-hidden="true">chat</mat-icon>
          {{ messaging() ? 'Opening…' : 'Message ' + otherName() }}
        </button>
      </div>
    </section>
  `,
  styles: `
    .bar {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: var(--spacing-3) var(--spacing-4);
      padding: var(--spacing-4);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      background: var(--color-surface);
    }
    .bar--turn {
      border-color: var(--color-primary);
      background: color-mix(in srgb, var(--color-primary) 7%, var(--color-surface));
      box-shadow: var(--elevation-floating);
    }
    .bar__text {
      min-width: 0;
    }
    .bar__title {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
      margin: 0;
      color: var(--color-ink);
      font-weight: var(--font-weight-semibold);
    }
    .bar--turn .bar__title mat-icon {
      color: var(--color-primary);
    }
    .bar__hint {
      margin: 2px 0 0;
      color: var(--color-text-muted);
      font-size: var(--font-size-sm);
    }
    .bar__actions {
      display: flex;
      flex-wrap: wrap;
      gap: var(--spacing-2);
    }
    .bar__danger {
      --mat-button-text-label-text-color: var(--color-danger);
    }
    @media (max-width: 599px) {
      .bar__actions {
        width: 100%;
      }
      .bar__actions button {
        flex: 1 1 auto;
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OfferActionBarComponent {
  readonly allowedActions = input.required<readonly string[]>();
  readonly busy = input<OfferAction | null>(null);
  readonly yourTurn = input(false);
  readonly waiting = input(false);
  readonly otherName = input.required<string>();
  readonly messaging = input(false);

  readonly acceptRequested = output<void>();
  readonly counterRequested = output<void>();
  readonly declineRequested = output<void>();
  readonly withdrawRequested = output<void>();
  readonly messageRequested = output<void>();

  private readonly allowed = computed(() => new Set(this.allowedActions()));

  protected can(action: OfferAction): boolean {
    return this.allowed().has(action);
  }
}
