// apps/web-angular/src/app/features/offers/inbox/offer-summary-row.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import type { OfferSummary } from '@orenji/api-client';
import { CardImageComponent } from '../../../shared/catalog/card-image/card-image.component';
import { printingCode, printingImageUrl } from '../../../shared/inventory/inventory-labels';
import {
  expiryLabel,
  isLiveOffer,
  offerKindLabel,
  offerStatusInfo,
  offerTermsText,
} from '../../../shared/offers/offer-labels';
import { StatusChipComponent } from '../../../shared/offers/status-chip.component';
import { RelativeTimePipe } from '../../../shared/pipes/relative-time.pipe';
import { AvatarComponent } from '../../../shared/ui/avatar/avatar.component';

/**
 * One negotiation of the inbox: the card, the other collector (approximate place only), the
 * live terms, status, whose turn it is and the expiry. The whole row opens the offer page.
 */
@Component({
  selector: 'app-offer-summary-row',
  imports: [
    RouterLink,
    MatIconModule,
    AvatarComponent,
    CardImageComponent,
    RelativeTimePipe,
    StatusChipComponent,
  ],
  template: `
    @let o = offer();
    <a
      class="row"
      [class.row--turn]="o.yourTurn"
      [routerLink]="['/offers', o.id]"
      [attr.aria-label]="label()"
      data-testid="offer-row"
    >
      <app-card-image class="row__img" [src]="image()" [game]="o.item?.card?.game ?? ''" alt="" />
      <span class="row__main">
        <span class="row__title">
          <span class="row__card">{{ o.item?.card?.name ?? 'Card no longer available' }}</span>
          @if (code()) {
            <span class="row__code mono">{{ code() }}</span>
          }
        </span>
        <span class="row__who">
          <app-avatar
            size="xs"
            [src]="o.counterparty.avatarUrl"
            [name]="o.counterparty.displayName"
            [decorative]="true"
          />
          {{ o.viewerRole === 'SELLER' ? 'From' : 'To' }} {{ o.counterparty.displayName }}
          @if (o.counterparty.location?.publicLabel; as place) {
            <span class="row__muted">· {{ place }}</span>
          }
        </span>
        <span class="row__terms">
          <span class="row__kind">{{ kind() }}</span>
          <strong data-testid="offer-row-terms">{{ terms() }}</strong>
        </span>
      </span>
      <span class="row__side">
        <app-status-chip [label]="status().label" [icon]="status().icon" [tone]="status().tone" />
        @if (o.yourTurn) {
          <span class="row__turn" data-testid="your-turn">
            <mat-icon aria-hidden="true">notifications_active</mat-icon>
            Your turn
          </span>
        } @else if (live()) {
          <span class="row__muted">Waiting for {{ o.counterparty.displayName }}</span>
        }
        @if (live() && expiry(); as expiry) {
          <span class="row__muted">{{ expiry }}</span>
        } @else {
          <span class="row__muted">{{ o.updatedAt | relativeTime }}</span>
        }
      </span>
    </a>
  `,
  styles: `
    :host {
      display: block;
    }
    .row {
      display: grid;
      grid-template-columns: 56px minmax(0, 1fr) auto;
      align-items: center;
      gap: var(--spacing-4);
      padding: var(--spacing-3) var(--spacing-4);
      color: inherit;
      text-decoration: none;
      transition: background var(--motion-duration-fast) var(--motion-easing-standard);
    }
    .row:hover {
      background: var(--color-surface-variant);
    }
    .row:focus-visible {
      outline: var(--focus-width) solid var(--color-focus-ring);
      outline-offset: calc(var(--focus-width) * -1);
    }
    .row--turn {
      background: color-mix(in srgb, var(--color-primary) 6%, var(--color-surface));
      box-shadow: inset 3px 0 0 var(--color-primary);
    }
    .row__img {
      width: 56px;
    }
    .row__main {
      display: flex;
      flex-direction: column;
      gap: 4px;
      min-width: 0;
    }
    .row__title {
      display: flex;
      flex-wrap: wrap;
      align-items: baseline;
      gap: var(--spacing-2);
    }
    .row__card {
      overflow: hidden;
      color: var(--color-ink);
      font-weight: var(--font-weight-semibold);
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .row__code {
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .row__who {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
      font-size: var(--font-size-sm);
    }
    .row__terms {
      display: flex;
      align-items: center;
      gap: var(--spacing-2);
      font-size: var(--font-size-sm);
    }
    .row__kind {
      padding: 0 6px;
      border-radius: var(--radius-pill);
      background: var(--color-surface-variant);
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .row__side {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 4px;
      text-align: right;
    }
    .row__turn {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      color: var(--color-primary);
      font-size: var(--font-size-sm);
      font-weight: var(--font-weight-semibold);
    }
    .row__turn mat-icon {
      width: 16px;
      height: 16px;
      font-size: 16px;
    }
    .row__muted {
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    @media (max-width: 599px) {
      .row {
        grid-template-columns: 44px minmax(0, 1fr);
        gap: var(--spacing-3);
      }
      .row__img {
        width: 44px;
      }
      .row__side {
        grid-column: 2;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: flex-start;
        gap: var(--spacing-2);
        text-align: left;
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OfferSummaryRowComponent {
  readonly offer = input.required<OfferSummary>();

  protected readonly image = computed(() => {
    const item = this.offer().item;
    return item ? (item.images[0]?.url ?? printingImageUrl(item.printing)) : null;
  });
  protected readonly code = computed(() => printingCode(this.offer().item?.printing));
  protected readonly status = computed(() => offerStatusInfo(this.offer().status));
  protected readonly live = computed(() => isLiveOffer(this.offer().status));
  protected readonly kind = computed(() => offerKindLabel(this.offer().kind));
  protected readonly expiry = computed(() => expiryLabel(this.offer().expiresAt));
  protected readonly terms = computed(() => {
    const offer = this.offer();
    return offerTermsText({
      kind: offer.kind,
      cashAmount: offer.cashAmount,
      currency: offer.currency,
      cards: offer.tradeItemCount,
    });
  });
  protected readonly label = computed(() => {
    const offer = this.offer();
    const card = offer.item?.card.name ?? 'a card';
    const direction = offer.viewerRole === 'SELLER' ? 'from' : 'to';
    return (
      `Offer on ${card} ${direction} ${offer.counterparty.displayName}: ${this.terms()}, ` +
      `${this.status().label}${offer.yourTurn ? ', your turn' : ''}`
    );
  });
}

// apps/mobile/src/features/offers/OfferSummaryRow.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { memo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import type { OfferSummary } from '@/src/api/types';
import { Avatar } from '@/src/components/ui/Avatar';
import { CardImage } from '@/src/components/ui/CardImage';
import { printingCode, printingImageUrl } from '@/src/lib/catalog';
import { relativeTime } from '@/src/lib/relativeTime';
import { fontFamily, fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

import {
  expiryLabel,
  isLiveOffer,
  offerKindLabel,
  offerStatusInfo,
  offerTermsText,
} from './offerLabels';
import { StatusChip } from './StatusChip';

/** "CA$40.00" / "2 cards" of a summary. */
export function summaryTerms(offer: OfferSummary): string {
  return offerTermsText({
    kind: offer.kind,
    cashAmount: offer.cashAmount,
    currency: offer.currency,
    cards: offer.tradeItemCount,
  });
}

/**
 * One negotiation of the inbox (web: `app-offer-summary-row`): the card, who it is from / to
 * (place label only), the live terms, the status, "Your turn" or who is awaited, and the expiry.
 */
export const OfferSummaryRow = memo(function OfferSummaryRow({
  offer,
  onPress,
}: {
  offer: OfferSummary;
  onPress: (offer: OfferSummary) => void;
}) {
  const { palette } = useTheme();
  const item = offer.item;
  const image = item ? (item.images[0]?.url ?? printingImageUrl(item.printing)) : null;
  const code = printingCode(item?.printing);
  const status = offerStatusInfo(offer.status);
  const live = isLiveOffer(offer.status);
  const terms = summaryTerms(offer);
  const expiry = expiryLabel(offer.expiresAt);
  const card = item?.card.name ?? 'Card no longer available';
  const direction = offer.viewerRole === 'SELLER' ? 'From' : 'To';
  const label =
    `Offer on ${item?.card.name ?? 'a card'} ${direction.toLowerCase()} ` +
    `${offer.counterparty.displayName}: ${terms}, ${status.label}${offer.yourTurn ? ', your turn' : ''}`;

  return (
    <Pressable
      accessibilityRole="link"
      accessibilityLabel={label}
      onPress={() => onPress(offer)}
      testID={`offer-row-${offer.id}`}
      style={({ pressed }) => [
        styles.row,
        {
          backgroundColor: palette.surface,
          borderColor: offer.yourTurn ? palette.primary : palette.border,
        },
        pressed && styles.pressed,
      ]}
    >
      <CardImage src={image} alt="" game={item?.card.game} size="sm" />
      <View style={styles.main}>
        <Text numberOfLines={2} style={[textStyle('md'), styles.strong, { color: palette.ink }]}>
          {card}
          {code ? <Text style={[styles.mono, { color: palette.textMuted }]}> {code}</Text> : null}
        </Text>
        <View style={styles.who}>
          <Avatar
            src={offer.counterparty.avatarUrl}
            name={offer.counterparty.displayName}
            size={18}
          />
          <Text
            numberOfLines={1}
            style={[textStyle('xs'), styles.grow, { color: palette.textMuted }]}
          >
            {direction} {offer.counterparty.displayName}
            {offer.counterparty.location?.publicLabel
              ? ` · ${offer.counterparty.location.publicLabel}`
              : ''}
          </Text>
        </View>
        <Text style={[textStyle('sm'), { color: palette.ink }]}>
          <Text style={{ color: palette.textMuted }}>{offerKindLabel(offer.kind)} · </Text>
          <Text style={styles.strong} testID={`offer-row-terms-${offer.id}`}>
            {terms}
          </Text>
        </Text>
        <View style={styles.side}>
          <StatusChip info={status} testID={`offer-row-status-${offer.id}`} />
          {offer.yourTurn ? (
            <View style={styles.turn} testID={`offer-row-turn-${offer.id}`}>
              <MaterialCommunityIcons name="bell-ring-outline" size={14} color={palette.primary} />
              <Text style={[textStyle('xs'), styles.strong, { color: palette.primary }]}>
                Your turn
              </Text>
            </View>
          ) : live ? (
            <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
              Waiting for {offer.counterparty.displayName}
            </Text>
          ) : null}
        </View>
        <Text style={[textStyle('xs'), { color: palette.textMuted }]}>
          {live && expiry ? expiry : relativeTime(offer.updatedAt)}
        </Text>
      </View>
    </Pressable>
  );
});

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    gap: spacing[3],
    padding: spacing[3],
    borderRadius: radius.md,
    borderWidth: 1,
  },
  main: { flex: 1, gap: spacing[1] },
  strong: { fontWeight: fontWeight.semibold },
  mono: { fontFamily: fontFamily.mono, fontWeight: 'normal' },
  who: { flexDirection: 'row', alignItems: 'center', gap: spacing[1] },
  grow: { flex: 1 },
  side: { flexDirection: 'row', alignItems: 'center', gap: spacing[2], flexWrap: 'wrap' },
  turn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  pressed: { opacity: 0.8 },
});
