// apps/web-angular/src/app/features/messages/thread/thread-header.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { RouterLink } from '@angular/router';
import type { ConversationSummary } from '@orenji/api-client';
import { AvatarComponent } from '../../../shared/ui/avatar/avatar.component';

export type ThreadMenuAction =
  'mute' | 'unmute' | 'archive' | 'block' | 'unblock' | 'report' | 'rate';

/**
 * Thread header: back to the list, the other collector (avatar, online dot, "typing…", link to
 * their profile) and the conversation menu: mute, archive, "Rate" (when the conversation or
 * another interaction made the pair eligible), block/unblock and "Report collector".
 */
@Component({
  selector: 'app-thread-header',
  imports: [RouterLink, MatButtonModule, MatIconModule, MatMenuModule, AvatarComponent],
  template: `
    @let c = conversation();
    <header class="head">
      @if (showBack()) {
        <button
          matIconButton
          type="button"
          aria-label="Back to conversations"
          (click)="back.emit()"
        >
          <mat-icon>arrow_back</mat-icon>
        </button>
      }
      <a
        class="head__who"
        [routerLink]="['/collectors', c.other.handle]"
        [attr.aria-label]="'Open the profile of ' + c.other.displayName"
      >
        <span class="head__avatar">
          <app-avatar
            size="sm"
            [src]="c.other.avatarUrl"
            [name]="c.other.displayName"
            [decorative]="true"
          />
          @if (c.other.onlineStatus === 'ONLINE') {
            <span class="head__online" aria-hidden="true"></span>
          }
        </span>
        <span class="head__names">
          <span class="head__name">{{ c.other.displayName }}</span>
          <span class="head__status" [class.head__status--live]="typing()">{{ status() }}</span>
        </span>
      </a>
      <button
        matIconButton
        type="button"
        class="head__menu"
        [attr.aria-label]="'Conversation options for ' + c.other.displayName"
        [matMenuTriggerFor]="menu"
      >
        <mat-icon>more_vert</mat-icon>
      </button>
      <mat-menu #menu="matMenu" xPosition="before">
        @if (c.muted) {
          <button mat-menu-item type="button" (click)="action.emit('unmute')">
            <mat-icon aria-hidden="true">notifications_active</mat-icon>
            Unmute
          </button>
        } @else {
          <button mat-menu-item type="button" (click)="action.emit('mute')">
            <mat-icon aria-hidden="true">notifications_off</mat-icon>
            Mute
          </button>
        }
        <button mat-menu-item type="button" (click)="action.emit('archive')">
          <mat-icon aria-hidden="true">archive</mat-icon>
          Archive
        </button>
        @if (canRate()) {
          <button mat-menu-item type="button" (click)="action.emit('rate')">
            <mat-icon aria-hidden="true">star</mat-icon>
            Rate {{ c.other.displayName }}
          </button>
        }
        @if (blocked()) {
          <button mat-menu-item type="button" (click)="action.emit('unblock')">
            <mat-icon aria-hidden="true">lock_open</mat-icon>
            Unblock {{ c.other.displayName }}
          </button>
        } @else {
          <button mat-menu-item type="button" class="head__danger" (click)="action.emit('block')">
            <mat-icon aria-hidden="true">block</mat-icon>
            Block {{ c.other.displayName }}
          </button>
        }
        <button mat-menu-item type="button" class="head__danger" (click)="action.emit('report')">
          <mat-icon aria-hidden="true">flag</mat-icon>
          Report collector
        </button>
      </mat-menu>
    </header>
  `,
  styles: `
    .head {
      display: flex;
      align-items: center;
      gap: var(--spacing-1);
      min-height: 60px;
      padding: var(--spacing-2) var(--spacing-2) var(--spacing-2) var(--spacing-3);
      border-bottom: 1px solid var(--color-border);
      background: var(--color-surface);
    }
    .head__who {
      display: flex;
      flex: 1 1 auto;
      align-items: center;
      gap: var(--spacing-3);
      min-width: 0;
      padding: var(--spacing-1);
      border-radius: var(--radius-md);
      color: inherit;
      text-decoration: none;
    }
    .head__who:hover .head__name {
      text-decoration: underline;
    }
    .head__avatar {
      position: relative;
      flex: 0 0 auto;
    }
    .head__online {
      position: absolute;
      right: -1px;
      bottom: -1px;
      width: 11px;
      height: 11px;
      border: 2px solid var(--color-surface);
      border-radius: 50%;
      background: var(--color-online-online);
    }
    .head__names {
      display: flex;
      flex-direction: column;
      min-width: 0;
      line-height: 1.25;
    }
    .head__name {
      overflow: hidden;
      font-weight: var(--font-weight-semibold);
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .head__status {
      color: var(--color-text-muted);
      font-size: var(--font-size-xs);
    }
    .head__status--live {
      color: var(--color-primary);
    }
    .head__danger {
      color: var(--color-danger);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThreadHeaderComponent {
  readonly conversation = input.required<ConversationSummary>();
  readonly typing = input(false);
  readonly blocked = input(false);
  /** An unrated interaction with the other collector exists (`GET /ratings/eligibility`). */
  readonly canRate = input(false);
  readonly showBack = input(true);
  readonly back = output<void>();
  readonly action = output<ThreadMenuAction>();

  protected readonly status = computed(() => {
    const other = this.conversation().other;
    if (this.blocked()) {
      return 'Blocked';
    }
    if (this.typing()) {
      return 'typing…';
    }
    return other.onlineStatus === 'ONLINE' ? 'Online now' : `@${other.handle}`;
  });
}

// apps/mobile/src/features/messages/ThreadHeader.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import type { ConversationSummary } from '@/src/api/types';
import { Avatar } from '@/src/components/ui/Avatar';
import { BottomSheet } from '@/src/components/ui/BottomSheet';
import { ListRow } from '@/src/components/ui/Layout';
import { fontWeight, spacing, textStyle, useTheme } from '@/src/theme';

export type ThreadMenuAction =
  'mute' | 'unmute' | 'archive' | 'block' | 'unblock' | 'report' | 'rate';

/** The status line under the other collector's name (web: `ThreadHeaderComponent.status`). */
export function threadStatus(
  conversation: ConversationSummary,
  typing: boolean,
  blocked: boolean
): string {
  if (blocked) {
    return 'Blocked';
  }
  if (typing) {
    return 'typing…';
  }
  return conversation.other.onlineStatus === 'ONLINE'
    ? 'Online now'
    : `@${conversation.other.handle}`;
}

/**
 * The conversation options button, shown in the navigation header (`headerRight`): the top-right
 * corner under the header is where Expo Go floats its tools button, so no control goes there.
 */
export function ThreadMenuButton({ name, onPress }: { name: string; onPress: () => void }) {
  const { palette } = useTheme();
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={`Conversation options for ${name}`}
      onPress={onPress}
      hitSlop={8}
      testID="conversation-menu"
      style={({ pressed }) => [styles.menuButton, pressed && styles.pressed]}
    >
      <MaterialCommunityIcons name="dots-vertical" size={24} color={palette.ink} />
    </Pressable>
  );
}

/**
 * Thread header (the web's `app-thread-header`): the other collector (avatar, online dot,
 * "typing…", link to their profile) and the conversation options in a bottom sheet (opened by
 * {@link ThreadMenuButton}): mute, archive, rate them (when an interaction can still be rated),
 * block / unblock and report the collector.
 */
export function ThreadHeader({
  conversation,
  typing,
  blocked,
  canRate = false,
  menuOpen,
  onCloseMenu,
  onProfile,
  onAction,
}: {
  conversation: ConversationSummary;
  typing: boolean;
  blocked: boolean;
  /** An interaction with the other collector can still be rated ("Rate …"). */
  canRate?: boolean;
  menuOpen: boolean;
  onCloseMenu: () => void;
  onProfile: () => void;
  onAction: (action: ThreadMenuAction) => void;
}) {
  const { palette } = useTheme();
  const other = conversation.other;
  return (
    <View
      style={[styles.head, { borderBottomColor: palette.border, backgroundColor: palette.surface }]}
    >
      <Pressable
        accessibilityRole="link"
        accessibilityLabel={`View the profile of ${other.displayName}`}
        onPress={onProfile}
        testID="conversation-profile"
        style={({ pressed }) => [styles.who, pressed && styles.pressed]}
      >
        <View>
          <Avatar src={other.avatarUrl} name={other.displayName} size={36} />
          {other.onlineStatus === 'ONLINE' ? (
            <View
              testID="conversation-online"
              style={[
                styles.online,
                { backgroundColor: palette.online.online, borderColor: palette.surface },
              ]}
            />
          ) : null}
        </View>
        <View style={styles.grow}>
          <Text numberOfLines={1} style={[textStyle('md'), styles.strong, { color: palette.ink }]}>
            {other.displayName}
          </Text>
          <Text
            testID="conversation-status"
            style={[textStyle('xs'), { color: typing ? palette.primary : palette.textMuted }]}
          >
            {threadStatus(conversation, typing, blocked)}
            {conversation.muted ? ' · Muted' : ''}
          </Text>
        </View>
      </Pressable>
      <BottomSheet
        visible={menuOpen}
        onClose={onCloseMenu}
        title={other.displayName}
        testID="conversation-menu-sheet"
      >
        {conversation.muted ? (
          <ListRow
            icon="bell-ring-outline"
            label="Unmute"
            kind="button"
            onPress={() => onAction('unmute')}
            testID="conversation-unmute"
          />
        ) : (
          <ListRow
            icon="bell-off-outline"
            label="Mute"
            detail="No notifications for this conversation"
            kind="button"
            onPress={() => onAction('mute')}
            testID="conversation-mute"
          />
        )}
        <ListRow
          icon="archive-outline"
          label="Archive"
          detail="A new message brings it back"
          kind="button"
          onPress={() => onAction('archive')}
          testID="conversation-archive"
        />
        {canRate ? (
          <ListRow
            icon="star-outline"
            label={`Rate ${other.displayName}`}
            kind="button"
            onPress={() => onAction('rate')}
            testID="conversation-rate"
          />
        ) : null}
        {blocked ? (
          <ListRow
            icon="lock-open-variant-outline"
            label={`Unblock ${other.displayName}`}
            kind="button"
            onPress={() => onAction('unblock')}
            testID="conversation-unblock"
          />
        ) : (
          <ListRow
            icon="cancel"
            label={`Block ${other.displayName}`}
            kind="button"
            tone="danger"
            onPress={() => onAction('block')}
            testID="conversation-block"
          />
        )}
        <ListRow
          icon="flag-outline"
          label="Report collector"
          kind="button"
          tone="danger"
          onPress={() => onAction('report')}
          testID="conversation-report"
        />
      </BottomSheet>
    </View>
  );
}

const styles = StyleSheet.create({
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  who: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing[3] },
  online: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
  },
  grow: { flex: 1 },
  strong: { fontWeight: fontWeight.semibold },
  menuButton: { paddingHorizontal: spacing[2], paddingVertical: spacing[1] },
  pressed: { opacity: 0.8 },
});
