// apps/web-angular/src/app/shared/safety/trading-safety-notice.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { SafetyNoticeContext, SafetyNoticeService } from './safety-notice.service';

/** Wording per context (English UI; the linked page exists in English and French). */
const COPY: Record<SafetyNoticeContext, { title: string; text: string }> = {
  conversation: {
    title: 'Trade safely',
    text:
      'Meet in a busy public place in daylight, bring someone along for valuable cards, never ' +
      'share your home address, and check the cards before any money changes hands.',
  },
  trade: {
    title: 'Trade safely',
    text:
      'Meet in a busy public place in daylight, bring someone along for valuable cards, never ' +
      'share your home address, and check the cards before any money changes hands. Be wary of ' +
      'pressure and of requests to pay outside the agreed method.',
  },
};

/**
 * Short, dismissible trading safety reminder shown in a conversation and on the offer / trade
 * pages until the collector dismisses it (per user, per context, see
 * {@link SafetyNoticeService}). It never blocks anything: the page around it keeps working.
 * Links to the "Trading safely" page and offers Report / Block (the parent performs them).
 */
@Component({
  selector: 'app-trading-safety-notice',
  imports: [RouterLink, MatButtonModule, MatIconModule],
  template: `
    @if (!dismissed()) {
      <aside
        class="notice"
        role="note"
        aria-labelledby="safety-notice-title"
        data-testid="safety-notice"
        [attr.data-context]="context()"
      >
        <mat-icon class="notice__icon" aria-hidden="true">shield_person</mat-icon>
        <div class="notice__body">
          <p class="notice__title" id="safety-notice-title">{{ copy().title }}</p>
          <p class="notice__text">
            {{ copy().text }}
            <a class="notice__link" routerLink="/legal/trading-safely" data-testid="safety-guide"
              >Read our trading safety advice</a
            >.
          </p>
          @if (showReport() || showBlock()) {
            <p class="notice__actions">
              @if (showReport()) {
                <button
                  matButton
                  type="button"
                  [attr.aria-label]="'Report ' + otherName()"
                  (click)="reportRequested.emit()"
                >
                  <mat-icon aria-hidden="true">flag</mat-icon>
                  Report
                </button>
              }
              @if (showBlock()) {
                <button
                  matButton
                  type="button"
                  [attr.aria-label]="'Block ' + otherName()"
                  (click)="blockRequested.emit()"
                >
                  <mat-icon aria-hidden="true">block</mat-icon>
                  Block
                </button>
              }
            </p>
          }
        </div>
        <button
          matIconButton
          type="button"
          class="notice__dismiss"
          aria-label="Dismiss the safety notice"
          (click)="dismiss()"
        >
          <mat-icon>close</mat-icon>
        </button>
      </aside>
    }
  `,
  styles: `
    :host {
      display: block;
    }
    .notice {
      display: flex;
      align-items: flex-start;
      gap: var(--spacing-3);
      padding: var(--spacing-3) var(--spacing-2) var(--spacing-3) var(--spacing-4);
      border: 1px solid var(--color-border);
      border-left: 4px solid var(--color-primary);
      border-radius: var(--radius-md);
      background: color-mix(in srgb, var(--color-primary) 8%, var(--color-surface));
      font-size: var(--font-size-sm);
    }
    .notice__icon {
      flex: 0 0 auto;
      color: var(--color-primary);
    }
    .notice__body {
      display: flex;
      flex: 1 1 auto;
      flex-direction: column;
      gap: var(--spacing-1);
      min-width: 0;
    }
    .notice__title {
      margin: 0;
      font-weight: var(--font-weight-semibold);
    }
    .notice__text {
      margin: 0;
      color: var(--color-text-muted);
    }
    .notice__link {
      color: var(--color-primary);
      font-weight: var(--font-weight-medium);
    }
    .notice__actions {
      display: flex;
      flex-wrap: wrap;
      gap: var(--spacing-1);
      margin: var(--spacing-1) 0 0 calc(-1 * var(--spacing-2));
    }
    .notice__dismiss {
      flex: 0 0 auto;
      margin: calc(-1 * var(--spacing-1)) 0;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TradingSafetyNoticeComponent {
  private readonly service = inject(SafetyNoticeService);

  readonly context = input.required<SafetyNoticeContext>();
  /** Display name of the other collector (Report / Block button labels). */
  readonly otherName = input('this collector');
  readonly showReport = input(true, { transform: booleanAttribute });
  readonly showBlock = input(true, { transform: booleanAttribute });
  readonly reportRequested = output<void>();
  readonly blockRequested = output<void>();

  protected readonly copy = computed(() => COPY[this.context()]);
  protected readonly dismissed = computed(() => this.service.dismissed(this.context())());

  protected dismiss(): void {
    this.service.dismiss(this.context());
  }
}

// apps/mobile/src/features/safety/TradingSafetyNotice.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { useAccount } from '@/src/account/AccountProvider';
import { Button } from '@/src/components/ui/Button';
import { fontWeight, radius, spacing, textStyle, useTheme } from '@/src/theme';

import {
  useSafetyNoticeStore,
  useSafetyNoticeVisible,
  type SafetyNoticeContext,
} from './safetyNoticeStore';

/** Wording per context (English UI; the linked page exists in English and French). */
const COPY: Record<SafetyNoticeContext, { title: string; text: string }> = {
  conversation: {
    title: 'Trade safely',
    text:
      'Meet in a busy public place in daylight, bring someone along for valuable cards, never ' +
      'share your home address, and check the cards before any money changes hands.',
  },
  trade: {
    title: 'Trade safely',
    text:
      'Meet in a busy public place in daylight, bring someone along for valuable cards, never ' +
      'share your home address, and check the cards before any money changes hands. Be wary of ' +
      'pressure and of requests to pay outside the agreed method.',
  },
};

export interface TradingSafetyNoticeProps {
  context: SafetyNoticeContext;
  /** Display name of the other collector (Report / Block button labels). */
  otherName?: string;
  /** Report the other collector (the parent opens the report screen); hidden when absent. */
  onReport?: () => void;
  /** Block the other collector (the parent confirms); hidden when absent. */
  onBlock?: () => void;
  testID?: string;
}

/**
 * Short, dismissible trading safety reminder shown in a conversation and on the offer / trade
 * screens until the collector dismisses it (per account, per context, on this device; see
 * `safetyNoticeStore`). It never blocks anything: the screen around it keeps working. Links to the
 * "Trading safely" page and offers Report / Block (the parent performs them). Web:
 * `app-trading-safety-notice`.
 */
export function TradingSafetyNotice({
  context,
  otherName = 'this collector',
  onReport,
  onBlock,
  testID = 'safety-notice',
}: TradingSafetyNoticeProps) {
  const { palette } = useTheme();
  const router = useRouter();
  const userId = useAccount().me?.id ?? null;
  const visible = useSafetyNoticeVisible(userId, context);
  const dismiss = useSafetyNoticeStore((state) => state.dismiss);
  if (!visible || !userId) {
    return null;
  }
  const copy = COPY[context];
  return (
    <View
      accessible
      accessibilityRole="summary"
      accessibilityLabel={`${copy.title}. ${copy.text}`}
      testID={testID}
      style={[
        styles.notice,
        {
          borderColor: palette.border,
          borderLeftColor: palette.primary,
          backgroundColor: palette.surface,
        },
      ]}
    >
      <MaterialCommunityIcons name="shield-account-outline" size={22} color={palette.primary} />
      <View style={styles.body}>
        <Text style={[textStyle('sm'), styles.title, { color: palette.ink }]}>{copy.title}</Text>
        <Text style={[textStyle('sm'), { color: palette.textMuted }]}>{copy.text}</Text>
        <Text
          accessibilityRole="link"
          accessibilityLabel="Read our trading safety advice"
          testID={`${testID}-guide`}
          style={[textStyle('sm'), styles.link, { color: palette.accent }]}
          onPress={() =>
            router.push({ pathname: '/legal/[key]', params: { key: 'trading-safely' } })
          }
        >
          Read our trading safety advice
        </Text>
        {onReport || onBlock ? (
          <View style={styles.actions}>
            {onReport ? (
              <Button
                label="Report"
                icon="flag-outline"
                variant="ghost"
                accessibilityLabel={`Report ${otherName}`}
                onPress={onReport}
                testID={`${testID}-report`}
              />
            ) : null}
            {onBlock ? (
              <Button
                label="Block"
                icon="cancel"
                variant="ghost"
                accessibilityLabel={`Block ${otherName}`}
                onPress={onBlock}
                testID={`${testID}-block`}
              />
            ) : null}
          </View>
        ) : null}
      </View>
      <Pressable
        accessibilityRole="button"
        accessibilityLabel="Dismiss the safety notice"
        hitSlop={8}
        onPress={() => dismiss(userId, context)}
        testID={`${testID}-dismiss`}
        style={({ pressed }) => [styles.dismiss, pressed && styles.pressed]}
      >
        <MaterialCommunityIcons name="close" size={20} color={palette.textMuted} />
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  notice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[2],
    borderWidth: 1,
    borderLeftWidth: 4,
    borderRadius: radius.md,
    paddingVertical: spacing[3],
    paddingLeft: spacing[3],
    paddingRight: spacing[2],
  },
  body: { flex: 1, gap: spacing[1] },
  title: { fontWeight: fontWeight.semibold },
  link: { fontWeight: fontWeight.semibold, textDecorationLine: 'underline' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[1], marginTop: spacing[1] },
  dismiss: { padding: spacing[1], borderRadius: radius.pill },
  pressed: { opacity: 0.6 },
});
